check alive instead of sleeping 2 sec check for file and volume databases instead of sleeping 4 sec

diff --git a/bin/enstore-start b/bin/enstore-start
--- a/bin/enstore-start
+++ b/bin/enstore-start
@@ -25,9 +25,12 @@ if [ $ping_only -eq 0 ] ; then
     python $ENSTORE_DIR/src/configuration_server.py \
            --config_host=$enstore_config_host --config_port=$enstore_config_port --config_file=$enstore_config_file &
     echo $! >> $enstore_db/`uname -n`-configuration_pids
-    echo "pause 2 seconds to make sure it starts"
-    sleep 2 # this is necessary to start up with no error messages when running all servers
-  fi        # on a single node
+    ecmd config --alive --list
+    if [ $? -ne 0 ]; then
+      echo "Configuration Server didn't start properly - aborting..."
+      exit 1
+    fi
+  fi
 
 else
 
@@ -48,9 +51,12 @@ if [ $ping_only -eq 0 ] ; then
     echo "$What Log Server"
     python $ENSTORE_DIR/src/log_server.py --config_host=$enstore_config_host --config_port=$enstore_config_port &
     echo $! >> $enstore_db/`uname -n`-log_server_pids
-    echo "pause 2 seconds to make sure it starts"
-    sleep 2 # this is necessary to start up with no error messages when running all servers
-  fi        # on a single node
+    ecmd log --alive --list
+    if [ $? -ne 0 ]; then
+      echo "Log Server didn't start properly - aborting..."
+      exit 1
+    fi
+  fi
 
 else
 
@@ -71,6 +77,12 @@ if [ $ping_only -eq 0 ] ; then
     echo "$What Volume Clerk"
     python $ENSTORE_DIR/src/volume_clerk.py --config_host=$enstore_config_host --config_port=$enstore_config_port &
     echo $! >> $enstore_db/`uname -n`-volume_clerk_pids
+    sleep 1 # has to read in database
+    ecmd vcc --alive --list
+    if [ $? -ne 0 ]; then
+      echo "Volume Clerk didn't start properly - aborting..."
+      exit 1
+    fi
   fi
 
 else
@@ -93,6 +105,12 @@ if [ $ping_only -eq 0 ] ; then
     echo "$What File Clerk"
     python $ENSTORE_DIR/src/file_clerk.py --config_host=$enstore_config_host --config_port=$enstore_config_port &
     echo $! >> $enstore_db/`uname -n`-file_clerk_pids
+    sleep 1 # has to read in database
+    ecmd fcc --alive --list
+    if [ $? -ne 0 ]; then
+      echo "File Clerk didn't start properly - aborting..."
+      exit 1
+    fi
   fi
 
 else
@@ -114,6 +132,11 @@ for i in $enstore_libraries; do
   if [ $ping_only -eq 0 ] ; then
     python $ENSTORE_DIR/src/library_manager.py --config_host=$enstore_config_host --config_port=$enstore_config_port $i &
     echo $! >> $enstore_db/`uname -n`-library_manager_pids
+    ecmd lmc --alive --list $i
+    if [ $? -ne 0 ]; then
+      echo "Library Manager didn't start properly - aborting..."
+      exit 1
+    fi
 
   else
 
@@ -135,6 +158,11 @@ for i in $enstore_media_changers; do
   if [ $ping_only -eq 0 ] ; then
     python $ENSTORE_DIR/src/media_changer.py --config_host=$enstore_config_host --config_port=$enstore_config_port $i &
     echo $! >> $enstore_db/`uname -n`-media_changer_pids
+    ecmd mcc --alive --list $i
+    if [ $? -ne 0 ]; then
+      echo "Media Changer didn't start properly - aborting..."
+      exit 1
+    fi
 
   else
 
@@ -171,18 +199,28 @@ done
 
 if [ $ping_only -eq 0 ] ; then
   if [ $enstore_start_admin -eq 1 ] ; then
-    echo "pause 2 seconds to make sure database files (ie, the file and volume)have been created by the file and volume clerks"
-    sleep 2 # this is necessary to wait until all database share memory files are created
-    db_checkpoint -h $ENSTORE_DB  -p 5 &
-    echo $! >> $enstore_db/`uname -n`-db_check_pids
-    echo "Starting database checkpoint daemon  on `hostname`"
-    db_deadlock -h $ENSTORE_DB  -t 1 &
-    echo $! >> $enstore_db/`uname -n`-db_dlck_pids
-    echo "Starting database deadlock daemon  on `hostname`"
+    if [ -r $ENSTORE_DB/file -a -r $ENSTORE_DB/volume ] ;  then
 
-    echo "$What DB Admin Server"
-    python $ENSTORE_DIR/src/admin_clerk.py --config_host=$enstore_config_host --config_port=$enstore_config_port &
-    echo $! >> $enstore_db/`uname -n`-admin_pids
+      echo "Starting database checkpoint daemon  on `hostname`"
+      db_checkpoint -h $ENSTORE_DB  -p 5 &
+      echo $! >> $enstore_db/`uname -n`-db_check_pids
+
+      echo "Starting database deadlock daemon  on `hostname`"
+      db_deadlock -h $ENSTORE_DB  -t 1 &
+      echo $! >> $enstore_db/`uname -n`-db_dlck_pids
+
+      echo "$What DB Admin Server"
+      python $ENSTORE_DIR/src/admin_clerk.py --config_host=$enstore_config_host --config_port=$enstore_config_port &
+      echo $! >> $enstore_db/`uname -n`-admin_pids
+      ecmd acc --alive
+      if [ $? -ne 0 ]; then
+        echo "Admin Clerk didn't start properly - aborting..."
+        exit 1
+      fi
+
+    else
+      echo "ERROR: file and volume database are not present - can't start db tools"
+    fi
   fi
 
 else
