add options to start and stop

diff --git a/bin/enstore-start b/bin/enstore-start
--- a/bin/enstore-start
+++ b/bin/enstore-start
@@ -1,17 +1,28 @@
 #!/bin/sh
-
+set -u  # force better programming and ability to use check for not set
 if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
 
-if [ "${1:-}" = "--ping" ] ; then
-  ping_only=1
-  shift
-else
-  ping_only=0
-fi
+# bin/$RCSfile$   $Revision$
+# start enstore processes on the current node
 
-set -u  # force better programming and ability to use check for not set
 
-. $ENSTORE_DIR/etc/defaults
+opts_wo_args='ping'
+opts_w_args='xterm|just'
+USAGE="`basename $0`: [--{$opts_w_args} <arg>] [--{$opts_wo_args}]"
+while opt=`expr "${1-}" : '--\(.*\)'`;do
+    shift
+    eval "case \$opt in
+    \\?) echo \"$USAGE\"; exit 0;;
+    $opts_wo_args)
+        eval opt_\$opt=1;;
+    $opts_w_args)
+        if [ $# = 0 ];then echo option $opt requires argument; exit 1; fi
+        eval opt_\$opt=\"'\$1'\";shift ;;
+    *)  echo \"invalid option: \$opt\"; exit 1;;
+    esac"
+done
+
+. $ENSTORE_DIR/etc/defaults          # also sourced in ecmd -- twice better than none???
 
 place=`pwd`
 cd $enstore_db
@@ -19,11 +30,17 @@ cd $enstore_db
 ################################################################################################################################################
 
 # the configuration server needs to be the 1st thing started
-if [ $ping_only -eq 0 ] ; then
-  if [ $enstore_start_config -eq 1 ] ; then
+if [ ! "${opt_ping-}" ];then
+  if [ $enstore_start_config -eq 1 -a \( "${opt_just-}" = "" -o "`echo ${opt_just-}|grep conf`" \) ];then
     echo "Starting Configuration Server on $enstore_config_host, port $enstore_config_port, using file $enstore_config_file"
-    python $ENSTORE_DIR/src/configuration_server.py \
-           --config_host=$enstore_config_host --config_port=$enstore_config_port --config_file=$enstore_config_file &
+    cmd="python $ENSTORE_DIR/src/configuration_server.py \
+           --config_host=$enstore_config_host --config_port=$enstore_config_port --config_file=$enstore_config_file"
+    if [ "${opt_xterm-}" ] && echo ${opt_xterm-} | egrep 'all|conf'; then
+        title="Config Server"
+        eval "xterm -sl 2500 -T \"$title\" -e $cmd &"
+    else
+        eval "$cmd &"
+    fi
     echo $! >> $enstore_db/`uname -n`-configuration_pids
     sleep 1
   fi
@@ -40,10 +57,16 @@ fi
 
 # the logger needs to be next
 
-if [ $ping_only -eq 0 ] ; then
-  if [ $enstore_start_log -eq 1 ] ; then
+if [ ! "${opt_ping-}" ];then
+  if [ $enstore_start_log -eq 1 -a \( "${opt_just-}" = "" -o "`echo ${opt_just-}|grep log`" \) ];then
     echo "Starting Log Server"
-    python $ENSTORE_DIR/src/log_server.py --config_host=$enstore_config_host --config_port=$enstore_config_port &
+    cmd="python $ENSTORE_DIR/src/log_server.py --config_host=$enstore_config_host --config_port=$enstore_config_port"
+    if [ "${opt_xterm-}" ] && echo ${opt_xterm-} | egrep 'all|log'; then
+        title="Log Server"
+        eval "xterm -sl 2500 -T \"$title\" -e $cmd &"
+    else
+        eval "$cmd &"
+    fi
     echo $! >> $enstore_db/`uname -n`-log_server_pids
     sleep 1
   fi
@@ -60,10 +83,16 @@ fi
 
 # volume clerk
 
-if [ $ping_only -eq 0 ] ; then
-  if [ $enstore_start_volumeclerk -eq 1 ] ; then
+if [ ! "${opt_ping-}" ];then
+  if [ $enstore_start_volumeclerk -eq 1 -a \( "${opt_just-}" = "" -o "`echo ${opt_just-}|grep vol`" \) ];then
     echo "Starting Volume Clerk"
-    python $ENSTORE_DIR/src/volume_clerk.py --config_host=$enstore_config_host --config_port=$enstore_config_port &
+    cmd="python $ENSTORE_DIR/src/volume_clerk.py --config_host=$enstore_config_host --config_port=$enstore_config_port"
+    if [ "${opt_xterm-}" ] && echo ${opt_xterm-} | egrep 'all|vol'; then
+        title="Config Server"
+        eval "xterm -sl 2500 -T \"$title\" -e $cmd &"
+    else
+        eval "$cmd &"
+    fi
     echo $! >> $enstore_db/`uname -n`-volume_clerk_pids
     sleep 1
   fi
@@ -81,10 +110,16 @@ fi
 
 # file clerk
 
-if [ $ping_only -eq 0 ] ; then
-  if [ $enstore_start_fileclerk -eq 1 ] ; then
+if [ ! "${opt_ping-}" ];then
+  if [ $enstore_start_fileclerk -eq 1 -a \( "${opt_just-}" = "" -o "`echo ${opt_just-}|grep fil`" \) ];then
     echo "Starting File Clerk"
-    python $ENSTORE_DIR/src/file_clerk.py --config_host=$enstore_config_host --config_port=$enstore_config_port &
+    cmd="python $ENSTORE_DIR/src/file_clerk.py --config_host=$enstore_config_host --config_port=$enstore_config_port"
+    if [ "${opt_xterm-}" ] && echo ${opt_xterm-} | egrep 'all|fil'; then
+        title="File Clerk"
+        eval "xterm -sl 2500 -T \"$title\" -e $cmd &"
+    else
+        eval "$cmd &"
+    fi
     echo $! >> $enstore_db/`uname -n`-file_clerk_pids
     sleep 1
   fi
@@ -99,83 +134,95 @@ fi
 ################################################################################################################################################
 
 # library manager
-for i in $enstore_libraries; do
-  echo "Starting $i Library Manager"
+if [ "${opt_just-}" = "" -o "`echo ${opt_just-}|grep lib`" ];then
+  for i in $enstore_libraries; do
+    echo "Starting $i Library Manager"
 
-  if [ $ping_only -eq 0 ] ; then
-    python $ENSTORE_DIR/src/library_manager.py --config_host=$enstore_config_host --config_port=$enstore_config_port $i &
-    echo $! >> $enstore_db/`uname -n`-library_manager_pids
-    sleep 1
-    ecmd lmc --alive --list $i
-    if [ $? -ne 0 ]; then
-      echo "   ...$i Library Manager not reachable..."
-      exit 1
+    if [ ! "${opt_ping-}" ];then
+      cmd="python $ENSTORE_DIR/src/library_manager.py --config_host=$enstore_config_host --config_port=$enstore_config_port $i"
+      if [ "${opt_xterm-}" ] && echo ${opt_xterm-} | egrep 'all|lib'; then
+          title="Library Manager $i"
+          eval "xterm -sl 2500 -T \"$title\" -e $cmd &"
+      else
+          eval "$cmd &"
+      fi
+      echo $! >> $enstore_db/`uname -n`-library_manager_pids
+      sleep 1
+      ecmd lmc --alive --list $i
+      if [ $? -ne 0 ]; then
+        echo "   ...$i Library Manager not reachable..."
+        exit 1
+      fi
+    else
+      ecmd lmc --alive --list $i
+      if [ $? -ne 0 ] ; then
+        echo "   ...$i Library Manager not reachable..."
+        exit 1
+      fi
     fi
-
-  else
-
-    ecmd lmc --alive --list $i
-    if [ $? -ne 0 ] ; then
-      echo "   ...$i Library Manager not reachable..."
-      exit 1
-    fi
-
-  fi
-
-done
+  done
+fi
 
 ################################################################################################################################################
 
 # media changer
-for i in $enstore_media_changers; do
-  echo "Checking $i Media Changer"
+if [ "${opt_just-}" = "" -o "`echo ${opt_just-}|grep med`" ];then
+  for i in $enstore_media_changers; do
+    echo "Checking $i Media Changer"
 
-  if [ $ping_only -eq 0 ] ; then
-    python $ENSTORE_DIR/src/media_changer.py --config_host=$enstore_config_host --config_port=$enstore_config_port $i &
-    echo $! >> $enstore_db/`uname -n`-media_changer_pids
-    sleep 1
-    ecmd mcc --alive --list $i
-    if [ $? -ne 0 ]; then
-      echo "   ...$i Media Changer not reachable..."
-      exit 1
+    if [ ! "${opt_ping-}" ];then
+      cmd="python $ENSTORE_DIR/src/media_changer.py --config_host=$enstore_config_host --config_port=$enstore_config_port $i"
+      if [ "${opt_xterm-}" ] && echo ${opt_xterm-} | egrep 'all|med'; then
+          title="Media Changer $i"
+          eval "xterm -sl 2500 -T \"$title\" -e $cmd &"
+      else
+          eval "$cmd &"
+      fi
+      echo $! >> $enstore_db/`uname -n`-media_changer_pids
+      sleep 1
+      ecmd mcc --alive --list $i
+      if [ $? -ne 0 ]; then
+        echo "   ...$i Media Changer not reachable..."
+        exit 1
+      fi
+    else
+      ecmd mcc --alive --list $i
+      if [ $? -ne 0 ] ; then
+        echo "   ...$i Media Changer not reachable..."
+        exit 1
+      fi
     fi
-
-  else
-
-    ecmd mcc --alive --list $i
-    if [ $? -ne 0 ] ; then
-      echo "   ...$i Media Changer not reachable..."
-      exit 1
-    fi
-
- fi
-
-done
-
+  done
+fi
 
 ################################################################################################################################################
 
 # mover
-for i in $enstore_movers; do
-  echo "Starting $i Mover"
+if [ "${opt_just-}" = "" -o "`echo ${opt_just-}|grep mov`" ];then
+  for i in $enstore_movers; do
+    echo "Starting $i Mover"
 
-  if [ $ping_only -eq 0 ] ; then
-    python $ENSTORE_DIR/src/mover.py --config_host=$enstore_config_host --config_port=$enstore_config_port $i &
-    echo $! >> $enstore_db/`uname -n`-mover_pids
-
-  else
-    echo "   ...No ping test for $i Mover...(yet)"
-
-  fi
-
-done
+    if [ ! "${opt_ping-}" ];then
+      cmd="python $ENSTORE_DIR/src/mover.py --config_host=$enstore_config_host --config_port=$enstore_config_port $i"
+      if [ "${opt_xterm-}" ] && echo ${opt_xterm-} | egrep 'all|mov'; then
+          title="Mover $i"
+          eval "xterm -sl 2500 -T \"$title\" -e $cmd &"
+      else
+          eval "$cmd &"
+      fi
+      echo $! >> $enstore_db/`uname -n`-mover_pids
+    else
+      echo "   ...No ping test for $i Mover...(yet)"
+    fi
+  done
+fi
 
 ################################################################################################################################################
 # dbase
 #start database administrator
 
-if [ $ping_only -eq 0 ] ; then
-  if [ $enstore_start_admin -eq 1 ] ; then
+if [ ! "${opt_ping-}" ];then
+  if [ $enstore_start_admin -eq 1 -a \( "${opt_just-}" = "" -o "`echo ${opt_just-}|grep adm`" \) ];then
     if [ -r $ENSTORE_DB/file -a -r $ENSTORE_DB/volume ] ;  then
 
       echo "Starting database checkpoint daemon  on `hostname`"
diff --git a/bin/enstore-stop b/bin/enstore-stop
--- a/bin/enstore-stop
+++ b/bin/enstore-stop
@@ -1,7 +1,24 @@
 #!/bin/sh
-
-if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
 set -u  # force better programming and ability to use check for not set
+if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
+
+# bin/$RCSfile$   $Revision$
+# stop enstore processes on the current node
+
+# NOTE: xterm is currently provided just for restart (compatible with start)
+opts_w_args='xterm|just'
+USAGE="`basename $0`: [--$opts_w_args <arg>]"
+while opt=`expr "${1-}" : '--\(.*\)'`;do
+    shift
+    eval "case \$opt in
+    \\?) echo \"$USAGE\"; exit 0;;
+    $opts_w_args)
+        if [ $# = 0 ];then echo option $opt requires argument; exit 1; fi
+        eval opt_\$opt=\"'\$1'\";shift ;;
+    *)  echo \"invalid option: \$opt\"; exit 1;;
+    esac"
+done
+
 
 . $ENSTORE_DIR/etc/defaults
 
@@ -10,22 +27,32 @@ turnoff() { for pid in $1; do
                 pidkill $pid
             done; }
 
-turnoff "$enstore_db/`uname -n`-db_*_pids"            "databases"
-turnoff "$enstore_db/`uname -n`-admin*pids"           "admin"
-turnoff "$enstore_db/`uname -n`-file_clerk*pids"      "file_clerk"
-turnoff "$enstore_db/`uname -n`-volume_clerk*pids"    "volume_clerk"
-turnoff "$enstore_db/`uname -n`-mover*pids"           "movers"
-turnoff "$enstore_db/`uname -n`-media_changer*pids"   "media_changers"
-turnoff "$enstore_db/`uname -n`-library_manager*pids" "library manager"
-turnoff "$enstore_db/`uname -n`-configuration*pids"   "configuration server"
-turnoff "$enstore_db/`uname -n`-log_server*pids"      "log server"
-turnoff "$enstore_db/`uname -n`-*pids"                "what else"
+if [ "${opt_just-}" = "" -o "`echo ${opt_just-}|grep adm`" ];then
+    turnoff "$enstore_db/`uname -n`-db_*_pids"            "databases"
+    turnoff "$enstore_db/`uname -n`-admin*pids"           "admin"
+fi
+if [ "${opt_just-}" = "" -o "`echo ${opt_just-}|grep fil`" ];then
+    turnoff "$enstore_db/`uname -n`-file_clerk*pids"      "file_clerk"
+fi
+if [ "${opt_just-}" = "" -o "`echo ${opt_just-}|grep vol`" ];then
+    turnoff "$enstore_db/`uname -n`-volume_clerk*pids"    "volume_clerk"
+fi
+if [ "${opt_just-}" = "" -o "`echo ${opt_just-}|grep mov`" ];then
+    turnoff "$enstore_db/`uname -n`-mover*pids"           "movers"
+fi
+if [ "${opt_just-}" = "" -o "`echo ${opt_just-}|grep med`" ];then
+    turnoff "$enstore_db/`uname -n`-media_changer*pids"   "media_changers"
+fi
+if [ "${opt_just-}" = "" -o "`echo ${opt_just-}|grep lib`" ];then
+    turnoff "$enstore_db/`uname -n`-library_manager*pids" "library manager"
+fi
+if [ "${opt_just-}" = "" -o "`echo ${opt_just-}|grep conf`" ];then
+    turnoff "$enstore_db/`uname -n`-configuration*pids"   "configuration server"
+fi
+if [ "${opt_just-}" = "" -o "`echo ${opt_just-}|grep log`" ];then
+    turnoff "$enstore_db/`uname -n`-log_server*pids"      "log server"
+fi
 
+#    turnoff "$enstore_db/`uname -n`-*pids"                "what else"
 
-
-
-#for pid in $enstore_db/`uname -n`-*_pids; do
-#    if [ "$pid" = "$enstore_db/`uname -n`-*_pids" ] ; then break; fi
-#    pidkill $pid
-#done
 exit
