improved user i/f, look for work elsewhere

diff --git a/bin/flip_tab b/bin/flip_tab
--- a/bin/flip_tab
+++ b/bin/flip_tab
@@ -2,14 +2,41 @@
 
 if [ "${1:-}" = "-x" ]; then set -xv; shift; fi
 
+script=`basename $0`
+
 usage() { echo "Usage: login as enstore to d0ensrv4, stkensrv4, or cdfensrv4"
-	  echo "       enter `basename $0` [[un]lock]"
+	  echo "       enter $script [[un]lock]"
 	}
 
-[ "$USER" != enstore ] && usage && exit 1
+check_work() { while read work1 action1
+	       do
+		 if [ $work1 != $work ]; then
+		    rem=`ls -vI \*.\* $work1 | awk 'END {print NR}'`
+		    if [ $rem -gt 1 ]; then
+		       echo "`date` There are $rem groups to $action1."
+		    elif [ $rem -eq 1 ]; then
+		       echo "`date` There is one group to $action1."
+		    fi
+		 fi
+	       done << EOD
+/write_protect_work	  lock
+/write_permit_work	  unlock
+/purge_volumes_work	  remove
+EOD
+
+	       ns=`find $work -type f -name \*.done -mtime -1 -print | awk 'END {print NR}'`
+	       nf=`find $work -type f -name \*.fail -mtime -1 -print | awk 'END {print NR}'`
+	       msg="Today's $script work: $ns groups ${action}ed, $nf groups failed."
+	       echo "`date` $msg"
+	       if [ $ns -gt 0 -o $nf -gt 0 ]; then
+		 enstore alarm --raise --severity "I" --root-error "$msg"
+	       fi
+	     }
+
+
+[ "`whoami`" != enstore ] && usage && exit 1
 
 node=`hostname -s`
-
 case $node in
   stkensrv4)
      icap="0,1,0"
@@ -31,7 +58,7 @@ case $node in
      ;;
 esac
 
-output=/tmp/`basename $0`.output
+output=/tmp/${script}.output
 
 action=${1:-"lock"}
 case $action in
@@ -49,18 +76,27 @@ case $action in
 esac
 
 if [ ! -d $work ]; then
-  echo `date` ERROR. $work does not exist
+  echo "`date` ERROR. $work does not exist"
   exit 1
+fi
+
+cd $work
+
+rem=`ls -vI \*.\* | awk 'END {print NR}'`
+if expr $rem : 0 >/dev/null; then
+   echo "`date` There are no volumes to $action."
+   check_work
+   echo "`date` Good bye."
+   exit
 fi
 
 if [ "$icap" != "$ocap" ]; then
   /usr/bin/rsh $sun -l acsss "echo set cap mode automatic $icap '\r' logoff | bin/cmd_proc -l -q 2>/dev/null"
 fi
 
-cd $work
-
 for i in `ls -vI \*.\*`; do
-  t0=`date  +'%s'`
+  t0=`date +'%s'`
+  echo "`date` Group $i" >> $output
   . $i |tee -a $output 2>&1
   echo
   echo
@@ -68,34 +104,35 @@ for i in `ls -vI \*.\*`; do
     /usr/bin/rsh $sun -l acsss "echo set cap mode automatic $icap '\r' logoff | bin/cmd_proc -l -q 2>/dev/null"
     echo
     echo
-    /bin/echo -n "Press Enter when all tapes have been loaded with tab in ${action}ed position"
+    /bin/echo -n "Press Enter when all tapes have been loaded with tabs in ${action}ed position"
     read ans
     while /bin/true; do
       cap=`/usr/bin/rsh $sun -l acsss "echo q cap $icap '\r' logoff | bin/cmd_proc -l -q 2>/dev/null"`
       capstate=`echo $cap | sed -e 's#.*automatic ##' | cut -f1 -d\ `
       if [ "$capstate" = "available" ]; then break; fi
-      echo `date` Waiting for cap to be unloaded...
+      echo "`date` Waiting for cap to be unloaded..."
       sleep 5
     done
     /usr/bin/rsh $sun -l acsss "echo set cap mode manual $icap '\r' logoff | bin/cmd_proc -l -q 2>/dev/null"
     echo
     echo
   fi
-  t1=`date  +'%s'`
+  touch $i
+  t1=`date +'%s'`
   delta=`expr $t1 - $t0`
   deltam=`expr $delta / 60`
   deltas=`expr $delta % 60`
   echo That cycle took $deltam minutes $deltas seconds.
-  /bin/echo -n "Were all of these steps successful [y/n]? "
+  nvol=`awk '{split($0,vols); for (v in vols) if (vols[v] ~ /^[[:upper:]]+[[:digit:]]+$/) print vols[v]}' $i | awk 'END {print NR}'`
+  /bin/echo -n "Have $nvol tapes been loaded in cap $icap with tabs in ${action}ed position [y/n]? "
   if read ans && expr "$ans" : '[Yy]' >/dev/null; then
      echo "... success acknowledged"
      echo
      echo "Now updating write-protect status in enstore..."
      # extract the volumes successfully entered, and set them as write-protected or write-permitted
-     awk '{split($0,vols); for (v in vols) if (vols[v] ~ /^[[:upper:]]+[[:digit:]]+$/) print vols[v]}' $i | while read vol; do
+     awk '{split($0,vols); for (v in vols) if (vols[v] ~ /^[[:upper:]]+[[:digit:]]+$/) print vols[v]}' $i | sort | while read vol; do
        enstore vol --write-protect-$prot $vol
      done
-     touch $i
      mv $i ${i}.done
   else
      echo "... failure acknowledged"
@@ -103,12 +140,16 @@ for i in `ls -vI \*.\*`; do
   fi
   echo
   echo
-  rem=`ls -vI \*.\* | wc -l`
+  rem=`ls -vI \*.\* | awk 'END {print NR}'`
   if expr $rem : 0 >/dev/null; then
-     echo `date` There are no groups remaining. Thank you.
+     echo "`date` There are no more volumes to $action. Thank you."
      break
   else
-     /bin/echo -n "There are `expr $rem` groups remaining.  Do another [y/n]? "
+     if [ $rem -gt 1 ]; then
+       /bin/echo -n "There are $rem groups remaining. Do another [y/n]? "
+     else
+       /bin/echo -n "There is only one group remaining! Do it [y/n]? "
+     fi
      if read ans && expr "$ans" : '[Yy]' >/dev/null; then
 	continue
      else
@@ -117,6 +158,8 @@ for i in `ls -vI \*.\*`; do
   fi
 done
 
+check_work
+
 if [ "$icap" != "$ocap" ]; then
   msgflag=
   while /bin/true; do
@@ -124,7 +167,7 @@ if [ "$icap" != "$ocap" ]; then
     capstate=`echo $cap | sed -e 's#.*automatic ##' | cut -f1 -d\ `
     if [ "$capstate" = "available" ]; then break; fi
     if [ -z "$msgflag" ]; then
-      echo `date` Waiting for cap to be unloaded ...
+      echo "`date` Waiting for cap to be unloaded ..."
       msgflag=done
     fi
     sleep 5
