=Bug fix

diff --git a/bin/pnfs b/bin/pnfs
--- a/bin/pnfs
+++ b/bin/pnfs
@@ -63,6 +63,47 @@ p_pnfs()    { df | grep -v localhost | grep  /pnfs/ | sed -e 's%.*/pnfs/%/pnfs/%
 " -f1; }
 
 
+pnameof()   { if [ -z "${1-}" ] ; then p_error "nameof id"; fi
+              eval cat  "\"`p_pnfs`.(nameof)($1)\"" ; }
+
+pparent()   { if [ -z "${1-}" ] ; then p_error "parent id"; fi
+              eval cat  "\"`p_pnfs`.(parent)($1)\"" ; }
+
+ppath()     { if [ -z "${1-}" ] ; then p_error "path id"; fi
+              filename=""
+              id=$1
+              while /bin/true;  do
+                #echo $filename
+                filename=`pnameof $id 2>/dev/null`/$filename
+                if [ $? -ne 0 ] ; then break; fi
+                id=`pparent $id`
+              done
+              #echo $filename
+              #filename=`echo $filename | sed -e 's/ //g' -e 's%root/fs/usr%pnfs%' -e 's%/$%%'`
+	      if [ `echo $filename | grep -c 'root/fs/usr'` -ne 1 ] ; then
+                echo "PNFS PROTECTION ERROR: admin should chmod go+rx /pnfs/fs/usr and subdirs"
+	      else
+ 	        filename=`echo $filename | sed -e 's/ //g' -e 's%root/fs/usr/%%' -e 's%/$%%'`
+              fi
+              if [ -z "$filename" ] ; then
+                filename="NO_SUCH_FILE"
+                echo $filename
+	      else
+	        mp=`echo $filename | cut -f2 -d/`
+  	        #echo $mp
+		cat /etc/mtab | grep pnfs | grep -v localhost | while read remote local rest; do
+		  rem=`echo $remote | sed -e 's%.*:/%%'`
+		  if [ $rem = $mp ] ; then 
+		    cmd="echo $filename | sed -e 's%/$mp%$local%'"
+		    #echo $cmd
+ 		    filename=`eval $cmd`
+		    echo $filename
+		    break
+ 		  fi
+                done
+              fi
+            }
+
 pfiles()    { if [ -z "${1-}" ] ; then p_error "files volume_path_in_volmap"; fi
               for i in $1/*; do
 	        a=`pnfs cat $i 4`
