look for work first under isa-tools, then under /

diff --git a/bin/take_out b/bin/take_out
--- a/bin/take_out
+++ b/bin/take_out
@@ -5,13 +5,14 @@ if [ "${1:-}" = "-x" ]; then set -xv; shift; fi
 script=`basename $0`
 
 usage() { echo "Usage: login as enstore to d0ensrv4, stkensrv4, or cdfensrv4"
-	  echo "       enter $script"
+	  echo "       enter $script [remove|shelve]"
 	}
 
-check_work() { while read work1 action1
+check_work() { local work1 action1
+	       while read work1 action1
 	       do
-		 if [ $work1 != $work ]; then
-		    rem=`ls -vI \*.\* $work1 | awk 'END {print NR}'`
+		 if [ $work1 != $(basename $work) -a -d $(dirname $work)/$work1 ]; then
+		    rem=`ls -vI \*.\* $(dirname $work)/$work1 | awk 'END {print NR}'`
 		    if [ $rem -gt 1 ]; then
 		       echo "`date` There are $rem groups to $action1."
 		    elif [ $rem -eq 1 ]; then
@@ -19,9 +20,10 @@ check_work() { while read work1 action1
 		    fi
 		 fi
 	       done << EOD
-/write_protect_work	  lock
-/write_permit_work	  unlock
-/purge_volumes_work	  remove
+write_protect_work	lock
+write_permit_work	unlock
+shelf_volumes_work	shelve
+purge_volumes_work	remove
 EOD
 
 	       ns=`find $work -type f -name \*.done -mtime -1 -print | awk 'END {print NR}'`
@@ -57,42 +59,80 @@ case $node in
      ;;
 esac
 
-output=/tmp/${script}.output
+action=${1:-"shelve"}
+case $action in
+  shelve)
+     work=$HOME/isa-tools/shelf_volumes_work
+     ;;
+  remove)
+     work=$HOME/isa-tools/purge_volumes_work
+     . $HOME/gettkt
+     ;;
+  *) usage
+     exit 1
+     ;;
+esac
 
-action=remove
-work=/purge_volumes_work
+# look for work at home first, then under /
+[ -d $work ] || work=/$(basename $work)
 
 if [ ! -d $work ]; then
   echo "`date` ERROR. $work does not exist"
   exit 1
 fi
 
-. $HOME/gettkt
-
 cd $work
 
 rem=`ls -vI \*.\* | awk 'END {print NR}'`
 if expr $rem : 0 >/dev/null; then
-   echo "`date` There are no volumes to $action."
+   echo "`date` There are no groups to $action. Good bye."
    check_work
-   echo "`date` Good bye."
    exit
+else
+   if [ $rem -gt 1 ]; then
+      /bin/echo -n "There are $rem groups to $action. Proceed [y/n]? "
+   else
+      /bin/echo -n "There is one group to $action. Proceed [y/n]? "
+   fi
+   if read ans && expr "$ans" : '[Yy]' >/dev/null; then
+      :
+   else
+      exit
+   fi
 fi
 
+output=/tmp/${script}.${action}.output
+
 for i in `ls -vI \*.\*`; do
-  t0=`date  +'%s'`
+  t0=`date +'%s'`
   echo "`date` Group $i" >> $output
-  echo "Now deleting volumes to be ejected from enstore..."
-  # extract the volumes about to be ejected, and delete them
+  # extract the volumes about to be ejected
   set `awk '{split($0,vols); for (v in vols) if (vols[v] ~ /^[[:upper:]]+[[:digit:]]+$/) printf "%s ",vols[v]}' $i`
-  if ! klist -s; then
-    echo "`date` ERROR. Check kerberos credentials."
-    exit 1
-  fi
-  if ! rsh $clerk ". /local/ups/etc/setups.sh; setup enstore; for vol in $*; do enstore vol --delete \$vol; done" 2>/dev/null; then
-    echo "`date` ERROR. Failed to delete volumes!"
-    exit 1
-  fi
+  case $action in
+    shelve)
+      echo "Now moving volumes to be ejected to shelf library..."
+      for vol in $*; do
+	if enstore info --check $vol; then
+	  lib=`enstore info --vol $vol | awk -F\' '$2 == "library" {print $4}'`
+	  if ! echo $lib | grep "^shelf-" >/dev/null; then
+	    enstore vol --new-library=shelf-$lib $vol
+	  fi
+	fi
+      done
+      ;;
+    remove)
+      echo "Now deleting volumes to be ejected from enstore..."
+      if ! klist -s; then
+	echo "`date` ERROR. Check kerberos credentials."
+	exit 1
+      fi
+      if ! rsh $clerk ". /local/ups/etc/setups.sh; setup enstore; for vol in $*; do enstore vol --delete \$vol; done" 2>/dev/null; then
+	echo "`date` ERROR. Failed to delete volumes!"
+	exit 1
+      fi
+      ;;
+  esac
+
   echo
   . $i |tee -a $output 2>&1
   echo
@@ -115,7 +155,7 @@ for i in `ls -vI \*.\*`; do
   echo
   rem=`ls -vI \*.\* | awk 'END {print NR}'`
   if expr $rem : 0 >/dev/null; then
-     echo "`date` There are no more volumes to $action. Thank you."
+     echo "`date` There are no more groups to $action. Thank you."
      break
   else
      if [ $rem -gt 1 ]; then
