auto checkin. I don't recall changing anything(?)

diff --git a/ups/configure b/ups/configure
--- a/ups/configure
+++ b/ups/configure
@@ -8,15 +8,15 @@ eval PROD_DIR=\$`echo $UPS_PROD_NAME | tr '[a-z]' '[A-Z]'`_DIR
 . $PROD_DIR/ups/Version
 
 # make sure we have a products link directory
-mkdir -p /usr/local/products/$PROD_NAME/$PROD_FLAVOR > /dev/null 2>&1 || true
-if cd /usr/local/products/$PROD_NAME/$PROD_FLAVOR
+mkdir -p /usr/local/products/$PROD_NAME > /dev/null 2>&1 || true
+if cd /usr/local/products/$PROD_NAME
 then
 	# make the link
 	rm -f $PROD_VERSION
 	ln -s $PROD_DIR $PROD_VERSION
 else
 	# can't do it for some reason...
-	echo "Notice: Unable to create /usr/local/products/$PROD_NAME/$PROD_VERSION/$PROD_VERSION link."
+	echo "Notice: Unable to create /usr/local/products/$PROD_NAME/$PROD_VERSION link."
 	echo "        Some functionality may be lost."
 fi 
 unset PROD_DIR
