Cleaned up handling of the xlogs directories.  Also, look for backup2tape_dir and optionally backup2tape_config_host in the config file; instead of using hardcoded values based on hostnames.

diff --git a/sbin/backup2Tape b/sbin/backup2Tape
--- a/sbin/backup2Tape
+++ b/sbin/backup2Tape
@@ -4,6 +4,8 @@ if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
 
 # bin/$RCSfile$  $Revision$
 
+#Make sure to set a timeout.
+timeout='--timeout 10 --retries 3'
 
 if [ -n "${1:-}" ];then 
   FULL=`echo $1 | tr a-z A-Z `
@@ -40,7 +42,9 @@ doit() { list "$1"
          if [ $status -ne 0 ]; then touch $QUIT; exit $status ;fi
        }
 
-saveit() { #  Tapes have to be declared to the volume server and in the correct storage family
+#Tapes have to be declared to the volume server and in the correct storage
+# family
+saveit() { 
            pnfsname=`echo $1 | tr '/' '-' | sed s/-//`
            ls -l $1
            doit "encp --data $verbose $1 $pnfspath/$pnfsname"
@@ -49,80 +53,67 @@ saveit() { #  Tapes have to be declared to the volume server and in the correct 
            if [ $status -ne 0 ]; then touch $QUIT; exit $status; fi
          }
 
+#This is the directory that this script finds where the backups are stored.
+backup_path=`enstore config $timeout --show backup dir`
+if [ $? -ne 0 ]; then
+   echo "No backup dir specified in configuration.  Aborting."
+   exit 1
+fi
+if [ ! -d "$backup_path" ]; then
+   echo "Backup directory $backup_path does not exist.  Aborting."
+   exit 1
+fi
+#This is the directory in PNFS that the backups are written into.
+pnfspath=`enstore config $timeout --show crons backup2tape_dir`
+if [ $? -ne 0 ]; then
+   echo "No backup2tape dir specified in configuration.  Aborting."
+   exit 1
+fi
+pnfspath=$pnfspath/`date_string_d` #Append the current date.
+if [ ! -d "$pnfspath" ]; then
+   mkdir -p "$pnfspath"
+   if [ $? -ne 0 ]; then
+     echo "Unable to make $pnfspath directory.  Aborting."
+     exit 1
+   fi
+fi
+export pnfspath
+#This is the config host for the Enstore system we plan to use.  By
+# default use default ENSTORE_CONFIG_HOST value.
+config_host=`enstore config $timeout --show crons backup2tape_config_host 2> /dev/null`
+if [ $? -eq 0 ]; then
+   ENSTORE_CONFIG_HOST=$config_host
+fi
+#This is the config host for the Enstore system we plan to use.  By
+# default use default ENSTORE_CONFIG_HOST value.
+config_port=`enstore config $timeout --show crons backup2tape_config_port 2> /dev/null`
+if [ $? -eq 0 ]; then
+   ENSTORE_CONFIG_PORT=$config_port
+fi
+
 verbose="--verbose=1"
-
-# filePath='/diska'
-# VAULT=${filePath}/BackupToTape
-# BACKUP_LOG=${VAULT}/backup_log;     export BACKUP_LOG
-# PNFS=${filePath}/pnfs-backup*/
-# ENSTORE=${filePath}/enstore-backup
-# ENSTORELOG=${filePath}/enstore-log-backup
-# QUIT=$VAULT/QUIT
-# TIMEONDISK=1  #days
-
-backup_path=`enstore config --show backup| grep "'dir':" | cut -d"'" -f 4`
-filePath=`dirname $backup_path`
+filePath=`dirname $backup_path` #All backup files are under this directory.
 VAULT=${filePath}/BackupToTape
 if [ ! -d $VAULT ]; then mkdir $VAULT; fi
 BACKUP_LOG=${VAULT}/backup_log;     export BACKUP_LOG
-PNFS=${filePath}/pnfs-backup*/
+PNFS=`find ${filePath} -name "pnfs-backup*" | grep -v xlogs` #strip xlogs
 ENSTORE=${filePath}/enstore-backup
 ENSTORELOG=${filePath}/enstore-log-backup
 QUIT=$VAULT/QUIT
 TIMEONDISK=1  #days
 
-## Fermi specific stuff
-#if [ $node = d0ensrv3 ]; then
-#  pnfspath="/pnfs/eagle/d0en-backups/`date_string_d`"; export pnfspath
-#  ENSTORE_CONFIG_HOST=stkensrv2.fnal.gov
-#
-#elif [ $node = d0ensrv3n ]; then
-#  pnfspath="/pnfs/eagle/d0en-backups/`date_string_d`"; export pnfspath
-#  ENSTORE_CONFIG_HOST=stkensrv2.fnal.gov
-#
-#elif [ $node = stkensrv3 ]; then
-#  pnfspath="/pnfs/eagle/backups/`date_string_d`"; export pnfspath
-#
-#elif [ $node = cdfensrv3 ]; then
-#  pnfspath="/pnfs/eagle/cdfen-backups/`date_string_d`"; export pnfspath
-#  ENSTORE_CONFIG_HOST=stkensrv2.fnal.gov
-#
-#elif [ $node = gccensrv2 ]; then
-#  pnfspath="/pnfs/eagle/gccen-backups/`date_string_d`"; export pnfspath
-#  ENSTORE_CONFIG_HOST=stkensrv2.fnal.gov
-#
-#else
-#  doit "echo Do not know about node $node... fix $ENSTORE_DIR/sbin/backup2Tape script"
-#  exit 1
-#fi
-
-case "$node" in
-	d0en*)
-		pnfspath="/pnfs/eagle/d0en-backups/`date_string_d`"; export pnfspath
-		ENSTORE_CONFIG_HOST=stkensrv2.fnal.gov
-		;;
-	stken*)
-		pnfspath="/pnfs/eagle/backups/`date_string_d`"; export pnfspath
-		;;
-	cdfen*)
-		pnfspath="/pnfs/eagle/cdfen-backups/`date_string_d`"; export pnfspath
-		ENSTORE_CONFIG_HOST=stkensrv2.fnal.gov
-		;;
-	gccen*)
-		pnfspath="/pnfs/eagle/gccen-backups/`date_string_d`"; export pnfspath
-		ENSTORE_CONFIG_HOST=stkensrv2.fnal.gov
-		;;
-	*)
-		doit "echo Do not know about node $node... fix $ENSTORE_DIR/sbin/backup2Tape script"
-		exit 1
-		;;
-esac
 
 rm -f $BACKUP_LOG
 
 # try to make a unique directory, but give up after 10 tries
-x=0; while [ $x -le 10 -a -d $pnfspath ]; do x=`expr $x + 1`; pnfspath=${pnfspath}.next; done
-if [ -d $pnfspath ]; then list "$pnfspath exists, quitting"; fi
+x=0
+while [ $x -le 10 -a -d $pnfspath ]; do
+   x=`expr $x + 1`
+   pnfspath=${pnfspath}.next
+done
+if [ -d $pnfspath ]; then
+   list "$pnfspath exists, quitting"
+fi
 mkdir -p $pnfspath
 
 rm -f $VAULT/*.tbz2 #old junk
@@ -152,27 +143,30 @@ fi
 
 PNFS_FILES=$VAULT/pnfs.files
 rm -f $PNFS_FILES
-###VP Here we create the xlogs tar files and put them in the corresponding pnfs-backup directories
+###VP
+# Here we create the xlogs tar files and put them in the corresponding
+# pnfs-backup directories.
 for xd in $PNFS
 do
-        fn=`find ${xd}xlogs $find_options -type f -name '*backup.Z' | sort | head -n1`
+        fn=`find ${xd}.xlogs $find_options -type f -name '*backup.Z' | sort | head -n1`
 #        echo Backup file=${fn}
         if [[ $fn != "" ]]
         then
           tarfile=`zcat ${fn} | fgrep LABEL | cut -f8 -d/ | cut -f1,2 -d .`
 #          echo Tar file=\"$tarfile\"
 	  startwal=`zcat ${fn} | fgrep 'START WAL' | cut -f6 -d' ' | cut -f1 -d')'`.Z
-	  startwal=${xd}xlogs/$startwal
+	  startwal=${xd}.xlogs/$startwal
 #	  echo Start WAL=\"$startwal\"
-          fl=`find ${xd}xlogs -follow -type f -newer $startwal`
+          fl=`find ${xd}.xlogs -follow -type f -newer $startwal`
           if [[ $fl != "" ]]
           then
-            tar cfz ${xd}xlogs-${tarfile}.tar.Z $startwal $fl
+            tar cfz ${xd}.xlogs-${tarfile}.tar.Z $startwal $fl
           fi
         fi
 done
 ###VP
-#only backup latest copy on disk, not all of them since we are running out of tape!
+# Only backup latest copy on disk, not all of them since we are running out
+# of tape!
 find $PNFS $find_options -maxdepth 1 -type f  -print | sort -r | while read f; do
     echo $f | cut -f1 -d.
   done | uniq | while read g; do 
