Made SDE ready.

diff --git a/sbin/check_for_traceback b/sbin/check_for_traceback
--- a/sbin/check_for_traceback
+++ b/sbin/check_for_traceback
@@ -1,12 +1,36 @@
 #!/bin/sh
 set -u  # force better programming and ability to use check for not set
 if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
-d=`date +"%Y-%m-%d"`
-LOGFILE="/diska/enstore-log/LOG-$d"
-MAILTO="berman@fnal.gov, huangch@fnal.gov, moibenko@fnal.gov, zalokar@fnal.gov, litvinse@fnal.gov"
-MAILFILE="/tmp/Traceback-$d"
+
+DATE=`date +"%Y-%m-%d"`
+LOGDIR=`enstore conf --show log_server log_file_path`
+if [ $? -ne 0 ]; then
+   echo "Unable to obtain log directory."
+   exit 1
+fi
+LOGFILE="$LOGDIR//LOG-$DATE"
+MAILTO=`enstore conf --show crons developer_email`
+if [ $? -ne 0 ]; then
+   echo "Unable to obtain email address(es)."
+   exit 1
+fi
+TMP_DIR=`enstore conf --show crons tmp_dir`
+if [ $? -ne 0 ]; then
+   TMP_DIR="/tmp"
+fi
+MAILFILE="$TMP_DIR/Traceback-$DATE"
+
 grep Traceback $LOGFILE > $MAILFILE
 if [ $? -eq 0 ]; then
    echo "For more details check $LOGFILE" >> $MAILFILE
-   /bin/mail -s "Traceback found. Please investigate!" $MAILTO <$MAILFILE
+   subject="Traceback found. Please investigate!"
+   if [ `uname` = "Linux" ]; then
+      /bin/mail -s $subject $MAILTO <$MAILFILE
+      rm $MAILFILE
+   else
+      echo "Subject: $subject" > $MAILFILE_s
+      cat $MAILFILE >> $MAILFILE_s
+      /usr/bin/mail $MAILTO <$MAILFILE_s
+      rm $MAILFILE $MAILFILE_s
+   fi
 fi
