Determine how many total movers that are configured and total movers currently down; then you know how many are currently available.  Use this number along with the number of movers busy to detemine if copy_fan_file should start the encp or abort to do low drive availability.

diff --git a/sbin/choose_ran_file b/sbin/choose_ran_file
--- a/sbin/choose_ran_file
+++ b/sbin/choose_ran_file
@@ -17,8 +17,10 @@ if [ "${1:-}" = "-C" ] ; then copyit=1; shift; else copyit=0; fi
 if [ "${1:-}" = "-F" ] ; then force_try=1; shift; else force_try=0; fi
 
 #  $1 should be the number of tapes to list/copy.
+COUNT=${1:-1}
 #  $2 should be one of: "onlylast" or "alsolast" or "onlyfirst" or "alsofirst" 
 #                       or "onlyfirstlast" or "alsofirstlast" or "onlyran"
+WHICH_FILE=${2:-"onlyran"}
 
 if [ "$ENSTORE_CONFIG_HOST"x == x ]; then
    source /usr/local/etc/setups.sh
@@ -29,25 +31,8 @@ if [ "$ENSTORE_CONFIG_HOST"x == x ]; then
    fi
 fi
 
-#node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
-#gang=`gang`
-#HTTP=http://${gang}srv2.fnal.gov
-#USE_WGET=1 #or 0 to do things with database values
-#FORGET=${2:-CLN}  #Not used anymore.
-#MUSTHAVE=${3:-""} #Not used anymore.
-#EXTRA=${5:-""}    #Not used anymore.
-#echo $EXTRA | egrep "full|readonly|migrated"
-#if [ $? -eq 0 ] ; then
-#    override_ro="--override-ro-mount"
-#fi
-
-COUNT=${1:-1}
-# valid values are "onlylast" or "alsolast" or "onlyfirst" or "alsofirst" 
-#  or "onlyfirstlast" or "alsofirstlast" or "onlyran"
-WHICH_FILE=${2:-"onlyran"}
-
 here=`pwd`
-override_ro=""
+override_ro="" #Not used anymore.
 tmp_dir=/tmp
 
 #Get the list of suitable tapes for testing.
@@ -229,10 +214,12 @@ while [ $done -gt 0 ]; do
     echo Last   file = $file_l
     echo 
 
+    #Obtain the library that this tape belongs too.
+    library=`enstore info  --vol $tape | grep library | cut -d' ' -f3`
+    library=`echo $library | tr ",'" "  " | sed "s/ //g"`
+
     #List the number of active volumes.  This will give more meaningful
     # output for the administrators.
-    library=`enstore info  --vol $tape | grep library | cut -d' ' -f3`
-    library=`echo $library | tr ",'" "  " | sed "s/ //"`
     cmd="enstore lib --vols $library"
     echo $cmd
     vols_at_movers=`eval $cmd`
@@ -241,20 +228,50 @@ while [ $done -gt 0 ]; do
     busy_movers=`echo "$vols_at_movers" | wc -l`
     #Subract the title line of output.
     busy_movers=`expr $busy_movers - 1`
+
+    #Determine the number of total drives for this library.
+    cmd2="enstore mov --list | grep ${library}.library_manager"
+    echo $cmd2
+    configured_movers=`eval $cmd2`
+    #Now count the number of lines.
+    total_movers=`echo "$configured_movers" | wc -l`
+    
+    down_movers=0
+    #Obtain the list of down movers.  Remove headers and empty lines.
+    servers_down=`enstore sched --show | egrep -v " Enstore | -----|^$"`
+    #Pull out just the server names.
+    echo "$servers_down" | awk '{print $1}' > /tmp/copy_ran_file_servers_down
+    #Loop over the configured movers looking for a match to a down mover.
+    for mover_line in "$configured_movers"; do
+	mover_name=`echo $mover_line | awk '{print $1'}`
+	grep $mover_name /tmp/copy_ran_file_servers_down > /dev/null
+	if [ $? -eq 0 ]; then
+            #If the grep returns success (0), increase the down movers
+            # count by one.
+            down_movers=`expr $down_movers + 1`
+        fi
+    done
+    #Determine the number of drives available right now.
+    online_movers=`expr $total_movers - $down_movers`
+
     #This test should compare this number to the number of drives in the
     # library.  I don't know of a good way from bash to get the number of
     # drives in a library, so for now using the value 6.  If -F was specified
     # on the command line (force_try = 1), we will force choose_ran_file to 
     # skip this test and force it to run the encp(s).
-    if [ $busy_movers -gt 6 -a $force_try -eq 0 ]; then
-      echo
-      echo "Aborting early from high mover usage."
-      echo
-      #5 seems like a good number. Its greater than 3 indicating 3 failures.
-      #  It is not -1, -2, 0, 10 or 7 which have special meaning in the plots.
-      #9-10-2002: Edited to return 0 instead of 5.  Emails were being 
-      # generated that make this the simpliest solution.
-      exit 0
+    mover_threshold=`expr $online_movers - 1` #Leave one idle.
+    if [ $busy_movers -gt $mover_threshold -a $force_try -eq 0 ]; then
+        echo
+	#Report the number of drives that are busy and those that exist.
+	echo "Busy Drives: $busy_movers  Total Drives: $total_movers  Down Drives: $down_movers  Online Drives: $online_movers"
+	echo
+	echo "Aborting early from high mover usage."
+	echo
+	#5 seems like a good number. Its greater than 3 indicating 3 failures.
+	# It is not -1, -2, 0, 10 or 7 which have special meaning in the plots.
+	#9-10-2002: Edited to return 0 instead of 5.  Emails were being 
+	# generated that make this the simpliest solution.
+	exit 0
     fi
 
     #for f in $thefiles; do
