add ability to get current  data instead of web data - still disabled, but code is there add ability to get last and first files in addition to random file add comments to make it more maintainable

diff --git a/sbin/choose_ran_file b/sbin/choose_ran_file
--- a/sbin/choose_ran_file
+++ b/sbin/choose_ran_file
@@ -1,5 +1,5 @@
 #!/bin/sh
-set -u  # force better programming and ability to use check for not set
+set -u
 if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
 
 if [ "${1:-}" = "-C" ] ; then copyit=1; shift; else copyit=0; fi
@@ -17,16 +17,30 @@ case $node in
 esac
 
 HTTP=http://${gang}srv2.fnal.gov
+USE_WGET=1 #or 0 to do things with database values
+
 COUNT=${1:-1}
 FORGET=${2:-CLN}
 MUSTHAVE=${3:-""}
+WHICH_FILE=${4:-"onlyran"} # valid values are "onlylast" or "alsolast" or "onlyfirst" or "alsofirst" or "onlyfirstlast" or "alsofirstlast" or "onlyran"
+
 here=`pwd`
 
-# first go get the volumes that are defined in the inventory
-echo `date` wget $HTTP/enstore/tape_inventory/VOLUMES_DEFINED 1>&2
-wget $HTTP/enstore/tape_inventory/VOLUMES_DEFINED 2>/dev/null
-rc=$?; if [ $rc -ne 0 ]; then echo "wget VOLUMES_DEFINED FAILED"l exit $rc;else echo `date` got it 1>&2 ; fi
-cat VOLUMES_DEFINED | egrep -iv "$FORGET|CLN|null|^Date|^label|DELETED|NOTALLOWED|NOACCESS|\.none\$" | egrep "$MUSTHAVE" >V_D
+# Get the volumes that are defined in the inventory
+if [ $USE_WGET -eq 1 ] ; then
+   echo `date` wget $HTTP/enstore/tape_inventory/VOLUMES_DEFINED
+   rm -f VOLUMES_DEFINED; wget $HTTP/enstore/tape_inventory/VOLUMES_DEFINED 2>/dev/null
+   rc=$?; if [ $rc -ne 0 ]; then echo "wget VOLUMES_DEFINED FAILED"l exit $rc;else echo `date` got it; fi
+else
+   echo "`date` enstore vol --vols > VOLUMES_DEFINED"
+   rm -f VOLUMES_DEFINED; enstore vol --vols > VOLUMES_DEFINED 2>/dev/null
+   rc=$?; if [ $rc -ne 0 ]; then echo "enstore vol --vols > VOLUMES_DEFINED FAILED"l exit $rc;else echo `date` got it; fi
+fi
+
+# get rid of all the entries that won't work (deleted, noaccess, notallowed, headers, trailers, null...)
+# get rid of all the entries that the user explicitly told us to forget ($FORGET)
+# look for all the entries that the user explicitly told us we must have
+egrep -iv "$FORGET|CLN|null|^Date|^label|DELETED|NOTALLOWED|NOACCESS|\.none\$" VOLUMES_DEFINED | egrep "$MUSTHAVE" >V_D
 rm -f VOLUMES_DEFINED
 N=`wc V_D| awk '{print $1}'`
 if [ $N -eq 0 ]; then
@@ -47,52 +61,98 @@ while [ $done -gt 0 ]; do
   # choose a random volume from the list
   ran=`python -c "import whrandom;print whrandom.randint(1,"$N")"`
   tape=`head -n $ran V_D|tail -n 1| awk '{print $1}'`
-  echo `date` enstore vol --vol $tape 2>&1
+
+  # get up to date information on the tape to make sure we have a chance to read a file
+  echo `date` enstore vol --vol $tape
   tinfo=`enstore vol --vol $tape`
-  echo "$tinfo" 2>&1
+  echo "$tinfo"
   if [ `echo $tinfo | egrep -c 'DELETED|NOTALLOWED|NOACCESS'` -ne 0 ]; then
-    echo REJECTED 2>&1
+    echo REJECTED $tape is DELETED/NOTALLOWED/NOACCESS
     continue
   fi
-  
-  echo `date` wget $HTTP/enstore/tape_inventory/$tape  2>/dev/null 1>&2
-  wget $HTTP/enstore/tape_inventory/$tape  2>/dev/null
-  rc=$?; if [ $rc -ne 0 ]; then echo "wget $tape FAILED "l exit $rc;else echo `date` got it 1>&2 ; fi
-  if [ `egrep -c 'NOACCESS|NOTALLOWED' $tape` -ne 0 ]; then echo `date` REJECTED NOACCESS/NOTALLOED 1>&2; rm -f $tape; continue; fi
+
+  # get the files list for that volume
+  if [ $USE_WGET -eq 1 ] ; then
+     echo `date` wget $HTTP/enstore/tape_inventory/$tape
+     rm -f $tape; wget $HTTP/enstore/tape_inventory/$tape  2>/dev/null
+     rc=$?; if [ $rc -ne 0 ]; then echo "wget $tape FAILED "; exit $rc;else echo `date` got it; fi
+  else
+     echo `date` "enstore file --list $tape > $tape"
+     rm -f $tape; enstore file --list > $tape  2>/dev/null
+     rc=$?; if [ $rc -ne 0 ]; then echo "enstore file --list $tape FAILED "; exit $rc;else echo `date` got it; fi
+     echo `date` "enstore vol --vol $tape >> $tape"
+     enstore vol --vol $tape >> $tape  2>/dev/null
+     rc=$?; if [ $rc -ne 0 ]; then echo "enstore vol --vol $tape FAILED "; exit $rc;else echo `date` got it; fi
+  fi
+
+  # make sure this volume is still on the readable list.
+  if [ `egrep -c 'DELETED|NOACCESS|NOTALLOWED' $tape` -ne 0 ]; then echo `date` REJECTED $tape is DELETED/NOACCESS/NOTALLOED; rm -f $tape; continue; fi
+
+  # get rid of volume information - we already processed that and don't need it anymore.
+  # get rid of all files the user already deleted. We don't want to read these files.
+  # if there aren't any files left, start over with a new tape.
   grep /pnfs $tape | egrep -v 'deleted|  yes /' > ${tape}_
   rm -f $tape
   NF=`wc ${tape}_| awk '{print $1}'`
-  if [ $NF -le 0 ]; then echo `date` REJECTED NO FILES 1>&2; rm  ${tape}_; continue; fi
+  if [ $NF -le 0 ]; then echo `date` REJECTED NO SUITABLE FILES on $tape; rm  ${tape}_; continue; fi
 
-  # choose a random file on the random volume
+  # sort the file according to location on the tape
+  sort -k4  ${tape}_ > ${tape}__
+  mv  ${tape}__  ${tape}_
+
+  # choose a random file and  1st and last non-deleted files on the random volume
   ran=`python -c "import whrandom;print whrandom.randint(1,"$NF")"`
   file=`head -n $ran ${tape}_|tail -n 1| awk '{print $NF,$1,$3,$4,$2}'`
-  F=`echo $file | awk '{print $1}'`
-  R=`echo $file | awk '{print $2,$3,$4,$5}'`
+  file1=`head -n 1 ${tape}_ | awk '{print $NF,$1,$3,$4,$2}'`
+  filel=`tail -n 1 ${tape}_ | awk '{print $NF,$1,$3,$4,$2}'`
+  rm -f ${tape}_
 
   # user could have renamed it - find current name using pnfsid
-  if [ ! -r $F ]; then
-    bfid=`echo $file | awk '{print $NF}'`
-    info=`enstore file --bfid $bfid 2>/dev/null`
-    if [ $? -ne 0 ]; then echo `date` REJECTED CAN NOT FIND BFID 1>&2; rm  ${tape}_; continue; fi
-    pnfsid=`echo $info | sed -e "s/.*pnfsid': '//" -e "s/'.*//"`
-    D=`dirname $F`
-    cd $D 2>/dev/null
-    if [ $? -ne 0 ]; then echo `date` REJECTED CAN NOT FIND DIRECTORY 1>&2; rm  ${tape}_; continue; fi
-    FN=`cat ".(nameof)($pnfsid)" 2>/dev/null`
-    if [ $? -ne 0 ]; then echo `date` REJECTED CAN NOT FIND FILENAME 1>&2; rm  ${tape}_; continue; fi
-    if [ ! -r $FN ]; then echo `date` REJECTED CAN NOT READ  FILE 1>&2; rm  ${tape}_; continue; fi
-    file="$FN $R"
-    F=$FN
-  fi
-  rm -f ${tape}_
+  files=""
+  for thefile in "$file" "$file1" "$filel"; do
+      F=`echo $thefile | awk '{print $1}'`
+      R=`echo $thefile | awk '{print $2,$3,$4,$5}'`
+      if [ ! -r $F ]; then
+        bfid=`echo $file | awk '{print $NF}'`
+        info=`enstore file --bfid $bfid 2>/dev/null`
+        if [ $? -ne 0 ]; then echo `date` REJECTED CAN NOT FIND BFID $bfid on $tape; continue 2; fi
+        pnfsid=`echo $info | sed -e "s/.*pnfsid': '//" -e "s/'.*//"`
+        D=`dirname $F`
+        cd $D 2>/dev/null
+        if [ $? -ne 0 ]; then echo `date` REJECTED CAN NOT FIND DIRECTORY $D from $tape; continue 2; fi
+        FN=`cat ".(nameof)($pnfsid)" 2>/dev/null`
+        if [ $? -ne 0 ]; then echo `date` REJECTED CAN NOT FIND FILENAME from pnfsid $pnfsid  from $tape;  continue 2; fi
+        if [ ! -r $FN ]; then echo `date` REJECTED CAN NOT READ FILE $FN from $tape;  continue 2; fi
+        file="$FN $R"
+        F=$FN
+      fi
+      files="$files $F"
+  done
+  ran_file=`echo $files |awk '{print $1}'`
+  first_file=`echo $files |awk '{print $2}'`
+  last_file=`echo $files |awk '{print $3}'`
+
+
+  # make a list of what the user wants:
+  # valid values are "onlylast" or "alsolast" or "onlyfirst" or "alsofirst" or "onlyfirstlast" or "alsofirstlast" or "onlyran"
+  case $WHICH_FILE in
+    onlyran)       thefiles=$ran_file ;;
+    onlyfirst)     thefiles=$first_file ;;
+    onlylast)      thefiles=$last_file ;;
+    onlyfirstlast) thefiles="$first_file $last_file" ;;
+    alsofirst)     thefiles="$ran_file $first_file" ;;
+    alsolast)      thefiles="$ran_file $last_file" ;;
+    alsofirstlast) thefiles="$ran_file $first_file $last_file" ;;
+    *)             thefiles=$ranfile ;;
+  esac
 
   # ok, just tell the user the name of the file and do another if needed
   # or copy the file to /dev/null if user requested this
   if [ $copyit -eq 0 ]; then
-    echo $file
+    echo $thefiles
   else
-    cmd="encp --verbose=3  --max-resubmit=7 $F /dev/null"
+    for f in $the_files; do
+    cmd="encp --verbose=3  --max-resubmit=7 --delayed-dismount=1 $f /dev/null"
     echo $cmd
     eval $cmd
     rc=$?
