This commit was manufactured by cvs2svn to create tag 'v3_6b_encp_Linux+2_6'.
Sprout from master 2006-07-27 19:07:06 UTC Michael Zalokar <zalokar> 'bumping version to v3_6b because of encpCut'
Cherrypick from master 2005-08-16 21:40:50 UTC Eileen Berman <berman> 'summary page of available encp release notes':
    etc/REL_V217.html
    etc/REL_V218.html
    etc/REL_V219.html
    etc/REL_V3_1.html
    etc/REL_V3_2.html
    etc/REL_V3_4.html
    etc/encpReleaseNotes.html
    src/accounting_server.py
    src/drivestat_server.py
Cherrypick from master 2006-02-27 23:56:16 UTC Dmitry Litvinsev <litvinse> '*** empty log message ***':
    etc/krb5.conf
    modules/EXfer.c
    sbin/choose_ran_file
    src/file_clerk.py
    src/file_clerk_client.py
    tools/pnfs_db_restore.py
Cherrypick from master 2002-01-28 23:35:44 UTC Jon Bakken <bakken> 'change in adic log processing':
    sbin/log-stash
Cherrypick from master 2004-01-28 17:28:29 UTC Alexander Moibenko <moibenko> 'updated test media changer':
    src/media_changer_test.py
Cherrypick from master 2005-08-18 20:23:52 UTC Michael Zalokar <zalokar> 'Changed the background image from enstore.gif to enstore_background.gif.':
    doc/WWW/encpReleaseNotes.html
Cherrypick from master 2006-04-24 18:01:11 UTC Michael Zalokar <zalokar> 'Patch to accept a single blank hardrive to install on.':
    etc/ks.cfg
Delete:
    sbin/xfer_stats.py
    src/file_clerk.py-1.217
    src/volume_clerk.py-1.349
    tools/scanner.c

diff --git a/sbin/choose_ran_file b/sbin/choose_ran_file
--- a/sbin/choose_ran_file
+++ b/sbin/choose_ran_file
@@ -2,59 +2,49 @@
 set -u
 if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
 
-if [ "${1:-}" = "-V" ] ; then verbose=1; shift; else verbose=0; fi
-
 if [ "${1:-}" = "-C" ] ; then copyit=1; shift; else copyit=0; fi
 
 if [ "${1:-}" = "-F" ] ; then force_try=1; shift; else force_try=0; fi
 
 # script to return a random file name(s) for tapes in the current inventory
 
-#node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
-#gang=`gang`
+node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
+gang=`gang`
 
-#HTTP=http://${gang}srv2.fnal.gov
-#USE_WGET=1 #or 0 to do things with database values
+HTTP=http://${gang}srv2.fnal.gov
+USE_WGET=1 #or 0 to do things with database values
 
 COUNT=${1:-1}
-FORGET=${2:-CLN}  #Not used anymore.
-MUSTHAVE=${3:-""} #Not used anymore
+FORGET=${2:-CLN}
+MUSTHAVE=${3:-""}
 EXTRA=${5:-""}
-# valid values are "onlylast" or "alsolast" or "onlyfirst" or "alsofirst" 
-#  or "onlyfirstlast" or "alsofirstlast" or "onlyran"
-WHICH_FILE=${4:-"onlyran"}
-echo WHICH_FILE $WHICH_FILE
+WHICH_FILE=${4:-"onlyran"} # valid values are "onlylast" or "alsolast" or "onlyfirst" or "alsofirst" or "onlyfirstlast" or "alsofirstlast" or "onlyran"
 here=`pwd`
 override_ro=""
-tmp_dir=/tmp
 echo $EXTRA | egrep "full|readonly|migrated"
 if [ $? -eq 0 ] ; then
     override_ro="--override-ro-mount"
 fi
-
-#Get the list of suitable tapes for testing.
-enstore info --query "select label,library,media_type,wrapper,write_protected
-from volume where 
-    label not like '%.deleted' and 
-    label not like 'CLN%' and 
-    label not like '%:%' and
-    system_inhibit_0 = 'none' and
-    user_inhibit_0 = 'none' and
-    last_access <> -1 and
-    media_type <> 'null' and
-    library not like '%shelf%'
-order by label;" \
-    | sed '1,2d' > $tmp_dir/V_D
-
-N=`wc /$tmp_dir/V_D| awk '{print $1}'`
-
-if [ $verbose -eq 1 ]; then
-    echo "Found $N suitable tapes."
-    cat /$tmp_dir/V_D
+# Get the volumes that are defined in the inventory
+if [ $USE_WGET -eq 1 ] ; then
+   echo `date` wget $HTTP/enstore/tape_inventory/VOLUMES_DEFINED
+   rm -f VOLUMES_DEFINED; wget $HTTP/enstore/tape_inventory/VOLUMES_DEFINED 2>/dev/null
+   rc=$?; if [ $rc -ne 0 ]; then echo "wget VOLUMES_DEFINED FAILED"l exit $rc;else echo `date` got it; fi
+else
+   echo "`date` enstore info --vols > VOLUMES_DEFINED"
+   rm -f VOLUMES_DEFINED; enstore info --vols > VOLUMES_DEFINED 2>/dev/null
+   rc=$?; if [ $rc -ne 0 ]; then echo "enstore info --vols > VOLUMES_DEFINED FAILED"l exit $rc;else echo `date` got it; fi
 fi
-   
+
+# get rid of all the entries that won't work (deleted, noaccess, notallowed, headers, trailers, null...)
+# get rid of all the entries that the user explicitly told us to forget ($FORGET)
+# look for all the entries that the user explicitly told us we must have
+egrep -v "$FORGET|CLN|NUL|^Date|^label|DELETED|NOTALLOWED|NOACCESS|\.none\$" VOLUMES_DEFINED | egrep "$MUSTHAVE" | egrep "$EXTRA" >V_D
+
+N=`wc V_D| awk '{print $1}'`
 if [ $N -eq 0 ]; then
-   rm /$tmp_dir/V_D
+   echo "NO files found after excluding \"$FORGET\"  and then searching for \"$MUSTHAVE\""
+   rm V_D
    exit 1
 fi
 
@@ -66,89 +56,94 @@ while [ $done -gt 0 ]; do
 
   cd $here
   loops=`expr $loops + 1`
-  if [ $loops -ge 1000 ]; then echo "TOO MANY LOOPS = $loops, EXIT"; 
-    rm -f $tmp_dir/V_D;
-    exit 1; 
-  fi
+  if [ $loops -ge 1000 ]; then echo "TOO MANY LOOPS = $loops, EXIT"; rm -f V_D;exit 1; fi
 
   # choose a random volume from the list
   ran=`python -c "import whrandom;print whrandom.randint(1,"$N")"`
-  tape=`head -n $ran /$tmp_dir/V_D|tail -n 1| awk '{print $1}'`
+  tape=`head -n $ran V_D|tail -n 1| awk '{print $1}'`
 
-  # Get up to date information on the tape to make sure we have a chance 
-  # to read a file.
-  if [ $verbose ]; then
-    echo `date` enstore info --vol $tape
-  fi
+  # get up to date information on the tape to make sure we have a chance to read a file
+  echo `date` enstore info --vol $tape
   tinfo=`enstore info --vol $tape`
-  if [ $verbose ]; then
-    echo "$tinfo"
-  fi
+  echo "$tinfo"
   if [ `echo $tinfo | egrep -c 'DELETED|NOTALLOWED|NOACCESS'` -ne 0 ]; then
     echo REJECTED $tape is DELETED/NOTALLOWED/NOACCESS
     continue
   fi
 
-  enstore info --list $tape | sed '1,2d' > $tmp_dir/$tape
+  # get the files list for that volume
+  if [ $USE_WGET -eq 1 ] ; then
+     echo `date` wget $HTTP/enstore/tape_inventory/$tape
+     rm -f $tape; wget $HTTP/enstore/tape_inventory/$tape  2>/dev/null
+     rc=$?; if [ $rc -ne 0 ]; then echo "wget $tape FAILED "; exit $rc;else echo `date` got it; fi
+  else
+     echo `date` "enstore file --list $tape > $tape"
+     rm -f $tape; enstore file --list > $tape  2>/dev/null
+     rc=$?; if [ $rc -ne 0 ]; then echo "enstore file --list $tape FAILED "; exit $rc;else echo `date` got it; fi
+     echo `date` "enstore info --vol $tape >> $tape"
+     enstore info --vol $tape >> $tape  2>/dev/null
+     rc=$?; if [ $rc -ne 0 ]; then echo "enstore info --vol $tape FAILED "; exit $rc;else echo `date` got it; fi
+  fi
 
   # make sure this volume is still on the readable list.
-  if [ `egrep -c 'DELETED|NOACCESS|NOTALLOWED' /$tmp_dir/$tape` -ne 0 ]; then 
-	echo `date` REJECTED $tape is DELETED/NOACCESS/NOTALLOED
-	rm -f /$tmp_dir/$tape
-	continue
-  fi
+  if [ `egrep -c 'DELETED|NOACCESS|NOTALLOWED' $tape` -ne 0 ]; then echo `date` REJECTED $tape is DELETED/NOACCESS/NOTALLOED; rm -f $tape; continue; fi
 
-  # Get rid of volume information - we already processed that and don't 
-  # need it anymore. #Get rid of all files the user already deleted. 
-  # We don't want to read these files.  If there aren't any files left, 
-  # start over with a new tape.  gnore hidden files and sort the filelist 
-  # according to location on the tape.
-  grep /pnfs $tmp_dir/$tape | egrep -v 'deleted|  yes /' | grep -v '\/\.' | sort -k4 > $tmp_dir/${tape}_
-  rm -f $tmp_dir/$tape
-  NF=`wc $tmp_dir/${tape}_| awk '{print $1}'`
-  if [ $NF -gt 0 ]; then 
-    echo `date`: $NF SUITABLE FILES on $tape
-  else
-    echo `date`: NO SUITABLE FILES on $tape
-    rm -f $tmp_dir/${tape}_
-    continue
-  fi
+  # get rid of volume information - we already processed that and don't need it anymore.
+  # get rid of all files the user already deleted. We don't want to read these files.
+  # if there aren't any files left, start over with a new tape.
+  grep /pnfs $tape | egrep -v 'deleted|  yes /' > ${tape}_
+  rm -f $tape
+  NF=`wc ${tape}_| awk '{print $1}'`
+  if [ $NF -le 0 ]; then echo `date` REJECTED NO SUITABLE FILES on $tape; rm  ${tape}_; continue; fi
 
-  # Choose a random file and  1st and last non-deleted files on the 
-  # random volume
+  # ignore hidden files and sort the filelist according to location on the tape
+  grep -v '\/\.' ${tape}_ | sort -k4 > ${tape}__
+  mv  ${tape}__  ${tape}_
+
+  # choose a random file and  1st and last non-deleted files on the random volume
   ran=`python -c "import whrandom;print whrandom.randint(1,"$NF")"`
-  file_r=`head -n $ran $tmp_dir/${tape}_ | tail -n 1 | awk '{print $NF,$1,$3,$4,$2}'`
-  file_f=`head -n 1 $tmp_dir/${tape}_ | awk '{print $NF,$1,$3,$4,$2}'`
-  file_l=`tail -n 1 $tmp_dir/${tape}_ | awk '{print $NF,$1,$3,$4,$2}'`
-  rm -f $tmp_dir/${tape}_
+  file=`head -n $ran ${tape}_|tail -n 1| awk '{print $NF,$1,$3,$4,$2}'`
+  file1=`head -n 1 ${tape}_ | awk '{print $NF,$1,$3,$4,$2}'`
+  filel=`tail -n 1 ${tape}_ | awk '{print $NF,$1,$3,$4,$2}'`
+  rm -f ${tape}_
 
-  #We are going to need these...
-  ran_bfid=`echo $file_r | awk '{print $5}'`
-  first_bfid=`echo $file_f | awk '{print $5}'`
-  last_bfid=`echo $file_l |awk '{print $5}'`
-   
-  #...and these...
-  ran_pnfsid=`enstore info --bfid $ran_bfid | grep pnfsid | cut -c 13-36`
-  first_pnfsid=`enstore info --bfid $first_bfid | grep pnfsid | cut -c 13-36`
-  last_pnfsid=`enstore info --bfid $last_bfid | grep pnfsid | cut -c 13-36`
- 
-  #...to get these.
-  ran_file=`enstore pnfs --path $ran_pnfsid`
-  first_file=`enstore pnfs --path $first_pnfsid`
-  last_file=`enstore pnfs --path $last_pnfsid`
+  # user could have renamed it - find current name using pnfsid
+  files=""
+  for thefile in "$file" "$file1" "$filel"; do
+      F=`echo $thefile | awk '{print $1}'`
+      R=`echo $thefile | awk '{print $2,$3,$4,$5}'`
+      if [ ! -r $F ]; then
+        bfid=`echo $file | awk '{print $NF}'`
+        info=`enstore file --bfid $bfid 2>/dev/null`
+        if [ $? -ne 0 ]; then echo `date` REJECTED CAN NOT FIND BFID $bfid on $tape; continue 2; fi
+        pnfsid=`echo $info | sed -e "s/.*pnfsid': '//" -e "s/'.*//"`
+        D=`dirname $F`
+        cd $D 2>/dev/null
+        if [ $? -ne 0 ]; then echo `date` REJECTED CAN NOT FIND DIRECTORY $D from $tape; continue 2; fi
+        FN=`cat ".(nameof)($pnfsid)" 2>/dev/null`
+        if [ $? -ne 0 ]; then echo `date` REJECTED CAN NOT FIND FILENAME from pnfsid $pnfsid  from $tape;  continue 2; fi
+        if [ ! -r $FN ]; then echo `date` REJECTED CAN NOT READ FILE $FN from $tape;  continue 2; fi
+        file="$FN $R"
+        F=$FN
+      fi
+      files="$files $F"
+  done
+  ran_file=`echo $files |awk '{print $1}'`
+  first_file=`echo $files |awk '{print $2}'`
+  last_file=`echo $files |awk '{print $3}'`
 
-  # Make a list of what the user wants.  Valid values are:
-  #  "onlylast" or "alsolast" or "onlyfirst" or "alsofirst" 
-  #  or "onlyfirstlast" or "alsofirstlast" or "onlyran"
+
+  # make a list of what the user wants:
+  # valid values are "onlylast" or "alsolast" or "onlyfirst" or "alsofirst" or "onlyfirstlast" or "alsofirstlast" or "onlyran"
   case $WHICH_FILE in
-    onlyran)       thefiles=$ran_file; thebfids=$ran_bfid;;
-    onlyfirst)     thefiles=$first_file; thebfids=$first_bfid;;
-    onlylast)      thefiles=$last_file; thebfids=$last_bfid;;
-    onlyfirstlast) thefiles="$first_file $last_file"; thebfids="$first_bfid $last_bfid";;
-    alsofirst)     thefiles="$ran_file $first_file"; thebfids="$ran_bfid $first_bfid";;
-    alsolast)      thefiles="$ran_file $last_file"; thebfids="$ran_bfid $last_bfid";;
-    alsofirstlast) thefiles="$ran_file $first_file $last_file"; thebfids="$ran_bfid $first_bfid $last_bfid";;
-    *)             thefiles=$ranfile; thebfids=$ran_bfid;;
+    onlyran)       thefiles=$ran_file ;;
+    onlyfirst)     thefiles=$first_file ;;
+    onlylast)      thefiles=$last_file ;;
+    onlyfirstlast) thefiles="$first_file $last_file" ;;
+    alsofirst)     thefiles="$ran_file $first_file" ;;
+    alsolast)      thefiles="$ran_file $last_file" ;;
+    alsofirstlast) thefiles="$ran_file $first_file $last_file" ;;
+    *)             thefiles=$ranfile ;;
   esac
 
   # ok, just tell the user the name of the file and do another if needed
@@ -158,9 +153,9 @@ while [ $done -gt 0 ]; do
   else
     echo
     echo Random volume = $tape 
-    echo Random file = $file_r
-    echo First  file = $file_f
-    echo Last   file = $file_l
+    echo Random file = $file
+    echo First  file = $file1 
+    echo Last   file = $filel
     echo 
 
     #List the number of active volumes.  This will give more meaningful
@@ -191,15 +186,8 @@ while [ $done -gt 0 ]; do
       exit 0
     fi
 
-    #for f in $thefiles; do
-    #  cmd="encp --verbose 10 --bypass-filesystem-max-filesize-check --max-resubmit 7 --delayed-dismount 1 $override_ro $f /dev/null"
-    #  echo $cmd
-    #  eval $cmd
-    #  rc=$?
-    #  RC=`expr $RC + $rc`
-    #done
-    for b in $thebfids; do
-      cmd="encp --verbose 10 --bypass-filesystem-max-filesize-check --max-resubmit 7 --delayed-dismount 1 $override_ro --get-bfid $b /dev/null"
+    for f in $thefiles; do
+      cmd="encp --verbose 10 --bypass-filesystem-max-filesize-check --max-resubmit 7 --delayed-dismount 1 $override_ro $f /dev/null"
       echo $cmd
       eval $cmd
       rc=$?
@@ -209,7 +197,7 @@ while [ $done -gt 0 ]; do
   done=`expr $done - 1`
 done
 
-rm -f $tmp_dir/V_D
+rm -f V_D
 cd $here
 
 exit $RC
