finalize file before production

diff --git a/sbin/generate_ticket b/sbin/generate_ticket
--- a/sbin/generate_ticket
+++ b/sbin/generate_ticket
@@ -23,14 +23,25 @@ remedy_server="csdserver"
 
 . /usr/local/etc/setups.sh
 
+rc=1
 setup remedy_soap
 if [ "$?" = "0" ];
 then
     export PYTHONPATH=$SETUPS_DIR:$PYTHONPATH
     CI=`echo $1 | awk '{ printf toupper($1) }'`
     $REMEDY_SOAP_DIR/bin/create_entry "${CI}" "$2" "$3" "$4"
-    exit 0
+    rc=$?
+    if [ "${rc}" != "0" ];
+    then
+	echo "enstore alarm --raise --root_error 'remedy_soap api call failed' --severity E"|at now+1min
+    fi
+else
+    echo "enstore alarm --raise --root_error 'remedy_soap product missing or not current' --severity E"|at now+1min
 fi
+
+#
+# try old api as well. Let's generate two pages....
+#
 
 setup remedy_api
 if [ "$?" = "1" ];
