Fix log file format acceptance bugs.

diff --git a/sbin/log_trans_fail b/sbin/log_trans_fail
--- a/sbin/log_trans_fail
+++ b/sbin/log_trans_fail
@@ -21,20 +21,18 @@ if [ $? -ne 0 ]; then
 fi
 
 #Second obtain the directory the logs are in.
-#HTML_DIR=`enstore conf $timeout --show crons html_dir`
-HTML_DIR=/home/zalokar/enstore-www
-#if [ $? -ne 0 ]; then
-#   echo "Unable to obtain log directory path." > /dev/null 2>&1
-#   return 1
-#fi
+HTML_DIR=`enstore conf $timeout --show crons html_dir`
+if [ $? -ne 0 ]; then
+   echo "Unable to obtain log directory path." > /dev/null 2>&1
+   return 1
+fi
 
 #Third obtain the directory the logs are in.
-#WEB_SERVER=`enstore conf $timeout --show crons web_node`
-WEB_SERVER=water
-#if [ $? -ne 0 ]; then
-#   echo "Unable to obtain log directory path." > /dev/null 2>&1
-#   return 1
-#fi
+WEB_SERVER=`enstore conf $timeout --show crons web_node`
+if [ $? -ne 0 ]; then
+   echo "Unable to obtain log directory path." > /dev/null 2>&1
+   return 1
+fi
 
 #Determine the name of the output file and a temporary output file.
 fname=$LOGS/transfer_failed.txt
@@ -56,14 +54,14 @@ rm -f $temp_drv_fname
 rm -f $temp_fname
 
 #Put the history at the beginning of the list.
-cp $LOGS/log_trans_fail_vol $temp_vol_fname
-cp $LOGS/log_trans_fail_drv $temp_drv_fname
+cp $LOGS/log_trans_fail_vol $temp_vol_fname 2> /dev/null
+cp $LOGS/log_trans_fail_drv $temp_drv_fname 2> /dev/null
 
 logfiles=`ls -1 LOG-*`
 for log in $logfiles; do
 
   skip=0
-  if [ $fname -nt $log ]; then skip=1; fi
+  if [ $fname -ot $log ]; then skip=1; fi
   if [ $skip -eq 1 ]; then continue; fi
 
   egrep "transfer.failed|SYSLOG.Entry" $log |
@@ -71,12 +69,19 @@ for log in $logfiles; do
      echo $line | grep SYSLOG > /dev/null 2>&1
      if [ $? -eq 0 ]; then
 	#What to look for if this was a "SYSLOG Entry" line.
-	volume=`echo "$line" | sed 's/.*\(\] [a-zA-Z0-9:.]*\) .*/\1/' | cut -c 3-`
 	location="N/A"
      else
 	#What to look for if this was a "transfer failed" line.
-        volume=`echo "$line" | sed 's/.*\(volume=[a-zA-Z0-9:.]*\) *.*/\1/' | cut -c 8-`
-	location=`echo "$line" | sed 's/.*\(location=.*\) *.*/\1/' | cut -c 10-`
+	location=`echo "$line" | sed -n 's/.*\(location=[0-9]*\) *.*/\1/p' | cut -c 10-`
+	if [ -z "$location" ]; then
+	    location="N/A"
+	fi
+     fi
+     #Pull out the volume name.  The first pattern matches tape labels.  The
+     # second pattern should match disk mover labels.
+     volume=`echo "$line" | sed -n -e 's/.*\([A-Z]\{1\}[A-Z0-9]\{4\}[0-9]\{1\}L\{0,1\}[12]\{0,1\}\).*/\1/p' -e 's/.*\([a-z.]+:[a-zA-Z0-9_/]+\.[a-zA-Z0-9_/]+\.[a-zA-Z0-9_/]+:[0-9]*\).*/\1/p'`
+     if [ -z "$volume" ]; then
+	volume="N/A"
      fi
      #Other items of interest.
      time=`echo $log | cut -c 5-`:`echo "$line" | awk '{print $1}'`
