rename config2 to TEMPconfig

diff --git a/sbin/mod_config b/sbin/mod_config
--- a/sbin/mod_config
+++ b/sbin/mod_config
@@ -113,11 +113,11 @@ file=$(basename $config)
 gitdir=$(dirname $dir)/config
 # Note:
 #   config refers to file name
-#   config2 refers to ansolute path of temp file for edit
+#   TEMPconfig refers to ansolute path of temp file for edit
 
 # - Leave it as in original script
-#-x config2=$gitdir/$file
-config2=`mktemp /tmp/${config}.XXXXXX` ||
+#-x TEMPconfig=$gitdir/$file
+TEMPconfig=`mktemp /tmp/${config}.XXXXXX` ||
     abort "can not mktemp for temporary file /tmp/${config}.XXXXXX"
 
 echo "The following configuration file will be modified: $dir/$config";
@@ -128,7 +128,7 @@ then
     echo "DEBUG:" dir=$dir
     echo "DEBUG:" gitdir=$gitdir
     echo "DEBUG:" config=$config
-    echo "DEBUG:" config2=$config2
+    echo "DEBUG:" TEMPconfig=$TEMPconfig
     echo
 fi
 #-------------------------------------------------------------
@@ -182,29 +182,29 @@ echo
 #   we will edit configuration file in e.g. /opt/enstore/config, or equvivalent.
 
 # edit temporary file allowing the user to make changes
-echo "DISPLAY=${DISPLAY:-<notset>}, about to edit with command $edcmd $config2"
+echo "DISPLAY=${DISPLAY:-<notset>}, about to edit with command $edcmd $TEMPconfig"
 
 # make a copy and edit it
-rm -f $config2
-cp -p $config $config2 || abort "can not copy file to edit"
+rm -f $TEMPconfig
+cp -p $config $TEMPconfig || abort "can not copy file to edit"
 
-$edcmd $config2
+$edcmd $TEMPconfig
 if [ $? -ne 0 ]; then abort "Something wrong with editing. Investigate"; fi
 echo "... success"
 echo
 
 # Check if updated file can be interpreted by python
 
-#echo "Checking $config2 is python file:"
-sed -n '1p' $config2 | grep python 
+#echo "Checking $TEMPconfig is python file:"
+sed -n '1p' $TEMPconfig | grep python 
 if [ $? -eq 0 ]; then
     # see if python finds any errors
-    echo "Checking $config2 by running python $config2"
-    python $config2
-    if [ $? -ne 0 ]; then abort "Running python on $config2 found errors."; fi
+    echo "Checking $TEMPconfig by running python $TEMPconfig"
+    python $TEMPconfig
+    if [ $? -ne 0 ]; then abort "Running python on $TEMPconfig found errors."; fi
     echo "... success"
 else
-    abort "edited file $config2 is not python script (no 'python' on first line)"
+    abort "edited file $TEMPconfig is not python script (no 'python' on first line)"
 fi
 echo
 #-------------------------------------------------------------
@@ -225,9 +225,9 @@ fi
 # - commit to remote repository
 # - copy to other nodes on cluster (where it is not used) 
 
-# copy temporary file $config2 to $config before committing
-cp -p $config2 $config
-rm -f $config2
+# copy temporary file $TEMPconfig to $config before committing
+cp -p $TEMPconfig $config
+rm -f $TEMPconfig
 
 # commit changes locally to git repository
 
@@ -270,7 +270,7 @@ echo "  on configuration host (locally)"
 # - Leave it as is in original script
 
 # @todo:
-cp -p $config2 $dir/$config || abort "cp -p $config2 $dir/$config failed"
+cp -p $TEMPconfig $dir/$config || abort "cp -p $TEMPconfig $dir/$config failed"
 
 # update config file on all machines
 
@@ -279,8 +279,8 @@ cp -p $config2 $dir/$config || abort "cp -p $config2 $dir/$config failed"
 #   Leave it as in original script.
 
 echo "  synchronizing $config to gang $gang"
-# config2 is absolute path
-rgang -c $gang $config2 $dir/$config
+# TEMPconfig is absolute path
+rgang -c $gang $TEMPconfig $dir/$config
 
 
 cmd_load_conf="enstore config --load --config_file=$ENSTORE_CONFIG_DIR/$config"
