bz1434  rb82: use rgang/enrcp, more changes
Distribute configuration file with enstore rgang/enrcp (instead of git pull to slave nodes).
Dompare file in configuration directory with git repo (index and files)
Change ENSTORE_CONFIG_DIR to point to top of subtree, like /home/enstore/site_specific and without 'config'
  The corresponding setting already done at setup-enstore script
Fix typo in dereferencing $gang

diff --git a/sbin/mod_config b/sbin/mod_config
--- a/sbin/mod_config
+++ b/sbin/mod_config
@@ -85,7 +85,8 @@ config_file=""
 opt_policy=0
 policy_file=""
 load=true
-gang=""
+remote_pull=false
+mygang=""
 editor=""
 verbose=0
 errors=0
@@ -100,7 +101,7 @@ do
         shift
         if [[ $# > 0 && $1 != -* ]]
         then
-            gang=$1
+            mygang=$1
             shift
         else
             echo "No argument given for --gang option" >&2
@@ -213,8 +214,8 @@ set -u
 
 #-------------------------------------------------------------
 # Set system name
-if [[ -z $(gang) ]] ; then
-    gang=$(gang)
+if [[ -z ${mygang} ]] ; then
+    mygang=$($ENSTORE_DIR/sbin/gang)
 fi
 
 if $test
@@ -242,7 +243,7 @@ if $debug
 then
     echo "
   test:   $test
-  gang:   $gang
+  gang:   $mygang
   config: $config_file
   policy: $policy_file
   load:   $load
@@ -307,7 +308,8 @@ then
     then
         echo "## Get policy_file name from configuration server"
         # try get policy file name by accessing configuration server
-        policy_file=$(${ENSTORE_DIR}/bin/conf.sh -k dispatcher | awk -F ":" '/policy_file/{print $2}' | tr -d "\,\'[:space:]" )
+        policy_file=$(${ENSTORE_DIR}/bin/conf.sh -k dispatcher | \
+                        awk -F ":" '/policy_file/{print $2}' | tr -d "\,\'[:space:]" )
     fi
 
     if [[ -z ${policy_file} ]]
@@ -334,7 +336,9 @@ else # by default, load configuration
         #   Default location is usually ~enstore/site_specific/config
         [[ ${ENSTORE_CONFIG_DIR} ]] || abort "ENSTORE_CONFIG_DIR not set"
 
-        dir=${ENSTORE_CONFIG_DIR}
+        # ${ENSTORE_CONFIG_DIR} points to the top level of git working tree
+        #   we keep configuration files in subdirectory config
+        dir=${ENSTORE_CONFIG_DIR}/config
         # Note, we do not append suffix ".conf" to file name anymore, must be full name
         [[ $(dirname file) == '.' ]] || echo abort "refuse to process relative path in file name ${config_file}"
         config=$(basename ${config_file})
@@ -347,7 +351,8 @@ else # by default, load configuration
     cmd_load_conf="enstore config --load --config_file=$dir/$config"
 fi
 
-# @todo: sanitize basename from cfile, presumably it was applied already. Check if we need dirname in gitdir [RB77]
+# @todo: sanitize basename from cfile, presumably it has already been applied.
+#  Check if we need dirname in gitdir [RB77]
 cfile=$(basename $config)
 gitdir=$(dirname $dir)/config
 
@@ -376,8 +381,11 @@ fi
 [[ -r $dir/$config ]] || abort "can not read $config"
 
 #=============================================================
-# Work in configuration directory. It is git working directory
+# Work in configuration directory. It must be git working directory
 cd $gitdir || abort "can not \"cd $gitdir\""
+
+git rev-parse --verify HEAD >/dev/null || abort "directory $gitdir is not git repository"
+git update-index -q --ignore-submodules --refresh
 
 # report current git branch
 cur_branch=$(git rev-parse --abbrev-ref HEAD)
@@ -404,9 +412,17 @@ $cmd   && success || abort "Something wrong with \"${cmd}\" ; - Investigate"
 
 [[ -r $cfile ]] || abort "file $gitdir/$cfile is unreadable in configuration directory"
 
+# obsolete: this is the same file when we work directly in git repository, skip
+#echo "compare configuration file fetched from remote repo and local configuration file"
+#cmd="diff -q $dir/$cfile $gitdir/$cfile"
+#$cmd || abort "Files differ: \"${cmd}\" ; - Investigate"
+#end_of_compare
+
 echo "compare configuration file fetched from remote repo and local configuration file"
-cmd="diff -q $dir/$cfile $gitdir/$cfile"
-$cmd || abort "Files differ: \"${cmd}\" ; - Investigate"
+git diff-files --quiet --ignore-submodules -- $cfile ||
+  abort "$cfile has unstaged changes in git"
+git diff-index --cached --quiet --ignore-submodules HEAD -- $cfile ||
+  abort "git index contains uncommitted changes for $cfile"
 end_of_compare
 
 # Make a copy of file
@@ -450,8 +466,8 @@ confirm_or_exit "About to commit changes, is this what you want [Y/n] " \
 # - commit to remote repository
 # - copy to all other nodes on cluster (where it is not used anyway exept policy file)
 
-echo "Copy $TEMPconfig to configuration directory:"
-cp -p $TEMPconfig $config || abort "cp -p $TEMPconfig $dir/$config failed"
+echo "Copy $TEMPconfig to $gitdir/$cfile:"
+cp -p $TEMPconfig $cfile || abort "cp -p $TEMPconfig $gitdir/$cfile failed"
 rm -f $TEMPconfig 2>/dev/null
 
 # commit changes locally to git repository
@@ -481,13 +497,26 @@ fi
 
 # remote=enconfig    # use first  git repository alias (central configuration server)
 remote=enconfig2     # use second git repostiory alais (can be central server or configuration host)
-remote_cmd="source /opt/enstore/sbin/gettkt ; cd \${ENSTORE_CONFIG_DIR} &&  git pull ${remote} ${cur_branch}"
 
-if [[ -n $gang && $gang != "UNKNOWN" ]] ; then
-    echo "  synchronizing $config to gang $gang with rgang:"
-    [[ $debug ]] && echo "rgang -s $gang ${remote_cmd}"
-    rgang -s $gang "${remote_cmd}"
+if [[ -n $mygang && $mygang != "UNKNOWN" ]] ; then
+    echo "  synchronizing $config to gang $mygang with rgang:"
+    if $remote_pull
+    then
+        # We do not normally use this, see "else"
+        # \${ENSTORE_CONFIG_DIR} is expanded on remote node
+        remote_cmd="source /opt/enstore/sbin/gettkt ; \
+cd \${ENSTORE_CONFIG_DIR} &&  \
+git pull ${remote} ${cur_branch}"
 
+        [[ $debug ]] && echo "  rgang -s $mygang ${remote_cmd}"
+        rgang -s $mygang "${remote_cmd}"
+    else
+        # Use enstore rgang/enrcp to copy file while skipping this host.
+        # $dir/$config is expanded on this (=configuraiton) host
+        cmd="rgang -C $mygang $config $dir/$config"
+        [[ $debug ]] && echo "  $cmd"
+        ${cmd}
+    fi
 else
     echo "gang is not set, skip synchronizing $config to gang with rgang"
 fi
@@ -510,11 +539,10 @@ confirm_or_exit "About to load new config file into server, is this what you wan
 #  if the file name is specified on command line, it is not what we load here
 #  but we leave it as in original script
 
-echo "Loading configuration file $ENSTORE_CONFIG_DIR/$config"
+echo "Loading configuration file $dir/$config"
 
 #$debug && echo ${cmd_load_conf}
 echo ${cmd_load_conf}
 ${cmd_load_conf}
 
 $debug && echo rc=$?
-
