refactoring

diff --git a/sbin/mod_config b/sbin/mod_config
--- a/sbin/mod_config
+++ b/sbin/mod_config
@@ -26,7 +26,9 @@ Options:
   -h | --help | -?      print this help message
        --config FILE    full name of configuration file [$ENSTORE_CONFIG_FILE]
                         File name must be full file name, no .conf is added.
-       --policy FILE    full name of SFA policy file [$ENSTORE_SFA_POLICY]
+       --policy         modify SFA policy file $ENSTORE_SFA_POLICY
+                        load policy file specified in configuration file, thus these two files
+                          MUST be the same.
        --gang           gang (system) name (stken, cdfen, d0en, ...)
        --editor EDITOR  use EDITOR to edit the file [env. $EDITOR or vi] and
                           also export it to be used by git to edit commit message
@@ -121,15 +123,16 @@ do
         ;;
     --policy)
         opt_policy=$((opt_policy+1))
-        shift
-        if [[ $# > 0 && $1 != -* ]]
-        then
-            policy_file=$1
-            shift
-        else
-            echo "No argument given for --policy option" >&2
-            errors=$((errors+1))
-        fi
+#       policy does not take second file argument now as we can not put it to config file
+#        shift
+#        if [[ $# > 0 && $1 != -* ]]
+#        then
+#            policy_file=$1
+#            shift
+#        else
+#            echo "No argument given for --policy option" >&2
+#            errors=$((errors+1))
+#        fi
         ;;
 
     --load)
@@ -152,6 +155,10 @@ do
     -x)
         set -xv
         shift
+        ;;
+    --) # End of all options
+        shift
+        break
         ;;
     -*)
         echo "Unknown option: $1" >&2
@@ -186,7 +193,7 @@ then
     if [[ $# > 0 ]]
     then
         # there is one argument left, consider it configuration file
-        policy_file=$1
+        config_file=$1
     # else no --opt_config, --opt_policy or file specified
     # the policy_file stays empty string for now until we validated ENSTORE_CONFIG_FILE
     fi
@@ -252,13 +259,14 @@ if [ -z "${ENSTORE_DIR-}"  ] ; then
     abort "ENSTORE_DIR not set and 'setup enstore' can not set it"
 fi
 
+
 #-------------------------------------------------------------
 # Check if we are running on configuration host, refuse otherwise
 
 on_config_host=false
 
-cfg_host=`echo $ENSTORE_CONFIG_HOST | cut -f1 -d\.`
-node=`$ENSTORE_DIR/sbin/hostname.py | cut -f1 -d\.`
+cfg_host=${echo $ENSTORE_CONFIG_HOST | cut -f1 -d\.}
+node=${$ENSTORE_DIR/sbin/hostname.py | cut -f1 -d\.}
 # my node is ...
 case $node in
     # I do not think we need this clause as it is harcoded, and it was broken as written
@@ -288,20 +296,42 @@ if [[ $load ]] ; then
 fi
 
 #-------------------------------------------------------------
+# from now on $config is either config file or policy file
+#   for the purpose editing the file or commiting it to git
 
-# We need a config file to change
-if [ -n "${ENSTORE_CONFIG_FILE-}" ]
+if [[ $opt_policy > 0 ]]
 then
-    config=`basename $ENSTORE_CONFIG_FILE`
-    dir=`dirname $ENSTORE_CONFIG_FILE`
-elif [ -z "${1-}" ]
+    # asserts:
+    [[ ${policy_file} ]] || abort "policy file name not provided"
+    [[ ${ENSTORE_SFA_POLICY ]]  || abort "environment ENSTORE_SFA_POLICY not set"
+
+    config=$(basename $ENSTORE_SFA_POLICY)
+    dir=$(dirname $ENSTORE_SFA_POLICY)
+
+    cmd_load_conf="enstore disp --load"
+
+else # by defualt, load configuration
+# elif [[ $opt_config > 0 ]] ; then
+    # configuration file name was provided on command line?
+    if [[ -n ${config_file} ]]
     then
-        abort_usg  "you need to specify a config file"
-    else
-        # Use default location which is usually ~enstore/site_specific/config :
+        # file name shall not include path, use directory from environment
+        #   Default location is usually ~enstore/site_specific/config
+        [[ ${ENSTORE_CONFIG_DIR} ]] || abort "ENSTORE_CONFIG_DIR not set"
+
         dir=${ENSTORE_CONFIG_DIR}
-        config=$1.conf
+        # Note, we do not append suffix ".conf" to fiule name anymore, must be full name
+        config=${config_file}
+    else
+        [[ ${ENSTORE_CONFIG_FILE ]]  || abort "ENSTORE_CONFIG_FILE not set"
+
+        config=$(basename $ENSTORE_CONFIG_FILE)
+        dir=$(dirname $ENSTORE_CONFIG_FILE)
+    fi
+    cmd_load_conf="enstore config --load --config_file=${dir}/${config}"
 fi
+
+
 
 #@todo: specify stken_policy.py
 # [[ ${ENSTORE_SFA_POLICY:-x} = "x" ]] || export ENSTORE_SFA_POLICY
@@ -441,6 +471,8 @@ echo "  synchronizing $config to gang $gang (remotely)"
 rgang -c $gang $TEMPconfig $dir/$config
 
 #---------------------------------------------------
+[[ $cmd_load_conf ]] || abort "$PROGNAME internal error: cmd_load_conf not set"
+
 cmd_load_conf="enstore config --load --config_file=$ENSTORE_CONFIG_DIR/$config"
 # check for situations where loading in the config file will not work.
 if [ $loadit -ne 1 ]; then
