Added support to check the authorized volume configuration file(s).

diff --git a/sbin/mod_config b/sbin/mod_config
--- a/sbin/mod_config
+++ b/sbin/mod_config
@@ -71,22 +71,45 @@ if [ $? -ne 0 ]; then abort "Something wrong with editting. Investigate"; fi
 echo "success"
 echo
 
-# see if python finds any errors
-echo "Checking $config by running python $config"
-python $config
-if [ $? -ne 0 ]; then abort "Running python found errors."; fi
-echo "success"
-echo
+# check if python file
+sed -n '1p' $config | grep python 
+if [ $? -eq 0 ]; then
+    # see if python finds any errors
+    echo "Checking $config by running python $config"
+    python $config
+    if [ $? -ne 0 ]; then abort "Running python found errors."; fi
+    echo "success"
+    echo
 
-# overkill - run through lint too
-echo "Checking $config by running python linter"
-rm -f $config2
-cp $config $config2
-python $ENSTORE_DIR/tools/mylint.py $config2
-if [ $? -ne 0 ]; then abort "Running lint found errors"; fi
-rm -f $config2
-echo "success"
-echo
+    # overkill - run through lint too
+    echo "Checking $config by running python linter"
+    rm -f $config2
+    cp $config $config2
+    python $ENSTORE_DIR/tools/mylint.py $config2
+    if [ $? -ne 0 ]; then abort "Running lint found errors"; fi
+    rm -f $config2
+    echo "success"
+    echo
+# check if it is an authorized volume file
+elif [ `echo $config | cut -c1-4` = "auth" ]; then
+    # make sure the auth file is correct
+    echo "Checking authorized file $config"
+    # ignore comment and empty lines
+    data="`grep -v "#" $config | grep -v "^[:space:]*$"`"
+    total=`echo "$data" | wc -l`
+    count="1"
+    while [ $count -le $total ]; do
+	# make sure each line has exactly 4 items on it.
+	line=`echo "$data" | sed -n ${count}p`
+	word_count=`echo "$line" | wc -w`
+	if [ $word_count -ne 4 ]; then
+	    abort "Error checking authorized volume file $config"
+	fi
+	count=`expr $count + 1`
+    done
+    echo "success"
+    echo
+fi
 
 # ok, time to commit - confirm
 echo -n 'About to commit changes, is this what you want [Y/n] '
