fix gridftp and add srmcp

diff --git a/sbin/pageDcache b/sbin/pageDcache
--- a/sbin/pageDcache
+++ b/sbin/pageDcache
@@ -33,6 +33,8 @@ rm_tmp_files() {
     rm -f $exit_code_ftp
     rm -f $output_gridftp
     rm -f $exit_code_gridftp
+    rm -f $output_srm
+    rm -f $exit_code_srm
 }
 
 echo_output() {
@@ -72,14 +74,11 @@ rm -f $test_file
 cp /var/log/messages $test_file
 if [ $? != 0 ]; then echo `date` ERROR: can not cp /var/log/messages; exit 2; fi
 
-output_dccp=/tmp/dcache_page_output_dccp${dcacheToTest}_$$
-exit_code_dccp=/tmp/dcache_page_exit_code_dccp${dcacheToTest}_$$
-output_kftp=/tmp/dcache_page_output_kftp${dcacheToTest}_$$
-exit_code_kftp=/tmp/dcache_page_exit_code_kftp${dcacheToTest}_$$
-output_ftp=/tmp/dcache_page_output_ftp${dcacheToTest}_$$
-exit_code_ftp=/tmp/dcache_page_exit_code_ftp${dcacheToTest}_$$
-output_gridftp=/tmp/dcache_page_output_gridftp${dcacheToTest}_$$
-exit_code_gridftp=/tmp/dcache_page_exit_code_gridftp${dcacheToTest}_$$
+for tp in dccp kftp ftp gridftp srm;
+do
+  eval output_${tp}=/tmp/dcache_page_output_${tp}${dcacheToTest}_$$
+  eval exit_code_${tp}=/tmp/dcache_page_exit_code_${tp}${dcacheToTest}_$$
+done
 rm_tmp_files
 
 # do the tests. spawn off the dccp test.  however the ftp test depends on the kftp
@@ -91,11 +90,15 @@ case $gang in
 	           w=$strip_dir/dcache-tests/$N.dcache_page_cms_$$
 		   wp=$strip_dir/dcache-tests/$N.dcache_page_p_cms_$$
 		   wa=$strip_dir/dcache-tests/$N.dcache_page_a_cms_$$
+		   wg=dcache-tests/$N.dcache_page_g_$$
+		   ws=/pnfs/fnal.gov/usr/eagle/dcache-tests/$N.dcache_page_s_$$
 		   dcache=cmsdca
 		   dcache_saag="dcache_cms"
 		   get_ports
 		   get_ticket
 		   `pageDcache_tests $- dccp $test_file $dcache $dcache_saag $w > $output_dccp 2>&1; echo $? > $exit_code_dccp`&
+		   `pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
+		   `pageDcache_tests $- srm $test_file $dcache $dcache_saag $ws > $output_srm 2>&1; echo $? > $exit_code_srm`&
 		   pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa > $output_kftp 2>&1; echo $? > $exit_code_kftp
 		   pageDcache_tests $- ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp 2>&1; echo $? > $exit_code_ftp
 		   ;;
@@ -103,11 +106,15 @@ case $gang in
 	           w=$strip_dir/dcache-tests/$N.dcache_page_cmstest_$$
 		   wp=$strip_dir/dcache-tests/$N.dcache_page_p_cmstest_$$
 		   wa=$strip_dir/dcache-tests/$N.dcache_page_a_cmstest_$$
+		   wg=dcache-tests/$N.dcache_page_g_$$
+		   ws=/pnfs/fnal.gov/usr/eagle/dcache-tests/$N.dcache_page_s_$$
 		   dcache=cmsdcdr1
 		   dcache_saag="dcache_cmstest"
 		   get_ports
 		   get_ticket
 		   `pageDcache_tests $- dccp $test_file $dcache $dcache_saag $w > $output_dccp 2>&1; echo $? > $exit_code_dccp`&
+		   `pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
+		   `pageDcache_tests $- srm $test_file $dcache $dcache_saag $ws > $output_srm 2>&1; echo $? > $exit_code_srm`&
 		   # they do not have kerberized or weak ftp doors on this system
 		   #pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa > $output_kftp 2>&1; echo $? > $exit_code_kftp
 		   #pageDcache_tests $- ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp 2>&1; echo $? > $exit_code_ftp
@@ -116,6 +123,7 @@ case $gang in
 	           w=$strip_dir/dcache-tests/$N.dcache_page_lqcd_$$
 		   wp=$strip_dir/dcache-tests/$N.dcache_page_p_lqcd_$$
 		   wa=$strip_dir/dcache-tests/$N.dcache_page_a_lqcd_$$
+		   ws=/pnfs/fnal.gov/usr/eagle/dcache-tests/$N.dcache_page_s_$$
 		   dcache=lqcd-cache
 		   dcache_saag="dcache_lqcd"
 		   get_ports
@@ -128,13 +136,15 @@ case $gang in
 	           w=$strip_dir/dcache-tests/$N.dcache_page_$$
 		   wp=$strip_dir/dcache-tests/$N.dcache_page_p_$$
 		   wa=$strip_dir/dcache-tests/$N.dcache_page_a_$$
-		   wg=/eagle/dcache-tests/$N.dcache_page_g_$$
+		   ws=/pnfs/fnal.gov/usr/eagle/dcache-tests/$N.dcache_page_s_$$
+		   wg=dcache-tests/$N.dcache_page_g_$$
 		   dcache=fndca
 		   dcache_saag="dcache_stk"
 		   get_ports
 		   get_ticket
 		   `pageDcache_tests $- dccp $test_file $dcache $dcache_saag $w > $output_dccp 2>&1; echo $? > $exit_code_dccp`&
-		   #`pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
+		   `pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
+		   `pageDcache_tests $- srm $test_file $dcache $dcache_saag $ws > $output_srm 2>&1; echo $? > $exit_code_srm`&
 		   pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa > $output_kftp 2>&1; echo $? > $exit_code_kftp
 		   pageDcache_tests $- ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp 2>&1; echo $? > $exit_code_ftp
 		   ;;
@@ -145,11 +155,15 @@ case $gang in
 	             w=$strip_dir/jon/fcdfsgi2/$N.dcache_page_$$
 		     wp=$strip_dir/jon/fcdfsgi2/$N.dcache_page_p_$$
 		     wa=$strip_dir/jon/fcdfsgi2/$N.dcache_page_a_$$
+		     wg=jon/fcdfsgi2/$N.dcache_page_g_$$
+		     ws=/pnfs/fnal.gov/usr/cdfen/jon/fcdfsgi2/$N.dcache_page_s_$$
 		     dcache=cdfdca
 		     dcache_saag="dcache_cdf"
 		     get_ports
 		     get_ticket
 		     `pageDcache_tests $- dccp $test_file $dcache $dcache_saag $w > $output_dccp 2>&1; echo $? > $exit_code_dccp`&
+		     #`pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
+		     #`pageDcache_tests $- srm $test_file $dcache $dcache_saag $ws > $output_srm 2>&1; echo $? > $exit_code_srm`&
 		     pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa > $output_kftp 2>&1; echo $? > $exit_code_kftp
 		     pageDcache_tests $- ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp 2>&1; echo $? > $exit_code_ftp
 		     ;;
@@ -160,11 +174,15 @@ case $gang in
 	            w=$strip_dir/archive/dcache-tests/$N.dcache_page_$$
 		    wp=$strip_dir/archive/dcache-tests/$N.dcache_page_p_$$
 		    wa=$strip_dir/archive/dcache-tests/$N.dcache_page_a_$$
+		    wg=archive/dcache-tests/$N.dcache_page_g_$$
+		    ws=/pnfs/fnal.gov/usr/archive/dcache-tests/$N.dcache_page_s_$$
 		    dcache=d0dca
 		    dcache_saag="dcache_d0"
 		    get_ports
 		    get_ticket
 		    `pageDcache_tests $- dccp $test_file $dcache $dcache_saag $w > $output_dccp 2>&1; echo $? > $exit_code_dccp`&
+		    #`pageDcache_tests $- gridftp $test_file $dcache $dcache_saag $wg > $output_gridftp 2>&1; echo $? > $exit_code_gridftp`&
+		    #`pageDcache_tests $- srm $test_file $dcache $dcache_saag $ws > $output_srm 2>&1; echo $? > $exit_code_srm`&
 		    pageDcache_tests $- kftp $test_file $dcache $dcache_saag $strip_dir $strong_port $wp $wa > $output_kftp 2>&1; echo $? > $exit_code_kftp
 		    pageDcache_tests $- ftp $test_file $dcache $dcache_saag $strip_dir $weak_port $wa > $output_ftp 2>&1; echo $? > $exit_code_ftp
 		    ;;
@@ -181,20 +199,23 @@ esac
 # jobs -p returns a space separated list of pids
 wait `jobs -p`
 
-# all the children have finished, echo anything they said.
+# all the children have finished, echo anything they said, 
+#                                 check the exit codes
+#                                 remove any tmp files
 echo_output $output_dccp
-echo_output $output_kftp
-echo_output $output_ftp
-echo_output $output_gridftp
-
-# and check their exit codes
 check_exit_code $exit_code_dccp
+echo_output $output_kftp
 check_exit_code $exit_code_kftp
+echo_output $output_ftp
 check_exit_code $exit_code_ftp
+echo_output $output_gridftp
 check_exit_code $exit_code_gridftp
+echo_output $output_srm
+check_exit_code $exit_code_srm
+
+rm_tmp_files
 
 # we are done, do any cleanup
-rm_tmp_files
 rm -f $test_file
 
 case $gang in
