Put the web server alias or hostname in the name of the final output file.

diff --git a/sbin/pnfs_monitor b/sbin/pnfs_monitor
--- a/sbin/pnfs_monitor
+++ b/sbin/pnfs_monitor
@@ -281,12 +281,26 @@ if [ `id -u` -ne 0 ]; then
 fi
 
 cd /pnfs/fs/usr #So, pathfinder works.
+if [ $? -ne 0 ]; then
+    echo "Failed to cd to /pnfs/fs/usr." 1>&2
+    exit 1
+fi
+
+#Get the alias name if available.
+www_alias=`enstore conf $timeout --show crons www_alias` #optional in config
+if [ $? -ne 0 ]; then
+   www_alias=`hostname | cut -f 1 -d "."`
+   #If the alias wasn't available, go with the hostname.
+   if [ -z "$www_alias" ]; then
+      www_alias=`hostanme | cut -f 1 -d "."`
+   fi
+fi
 
 #Specify where the temporary information should go.
 TEMP_OUTUPT_DIR=/var/tmp/pnfs_monitor
 mkdir -p $TEMP_OUTUPT_DIR
-TEMP_OUTPUT_FILE=/tmp/pnfs_monitor
-TEMP_OUTPUT_FILE_2=/tmp/pnfs_monitor_2
+TEMP_OUTPUT_FILE=/tmp/${www_alias}_pnfs_monitor      #copied to web server
+TEMP_OUTPUT_FILE_2=/tmp/pnfs_monitor_2  #copied to $TEMP_OUTUPT_DIR/
 rm -f $TEMP_OUTPUT_FILE
 #Make sure we know how up-to-date this is.
 echo -e "Missing files in pnfs report:" `date` >> $TEMP_OUTPUT_FILE 2>&1
