Made SDE ready.

diff --git a/sbin/pnfsExportList b/sbin/pnfsExportList
--- a/sbin/pnfsExportList
+++ b/sbin/pnfsExportList
@@ -1,12 +1,104 @@
 #!/bin/sh
 
-node=`uname -n| sed -e 's/\([^\.]\)\..*/\1/'`
-gang=`gang`
+#Number of columns to display the output into.
+NUMCOLUMNS=3
 
-f=/tmp/pnfsExports.html
+#Make sure to set a timeout.
+timeout='--timeout 10 --retries 3'
 
-python $ENSTORE_DIR/sbin/pnfsExports.py --all >$f 2>$f.errors
+#Make sure we are
+if [ `id -u` -ne 0 ]; then
+   echo "Must be user root." 2>&1
+   exit 1
+fi
 
-enrcp $f ${gang}srv2:/fnal/ups/prd/www_pages/enstore/
+#Verify that we can find pnfs.
+if [ ! -f /usr/etc/pnfsSetup ]; then
+   echo "Unable to find /usr/etc/pnfsSetup file." 2>&2
+   exit 1
+fi
+pnfs_location=`egrep "^pnfs=" /usr/etc/pnfsSetup | cut -f 2 -d "="`
+if [ -z "$pnfs_location" ]; then
+   echo "Unable to find pnfs installation." 1>&2
+fi
+pmount=$pnfs_location/tools/pmount
+mdb=$pnfs_location/tools/mdb
+if [ ! -f $pmount ]; then
+   echo "Unable to find pmount command." 1>&2
+   exit 1
+fi
+
+#Obtain the list of hosts allowed to mount pnfs.
+hostlist=`$pmount show hosts`
+if [ $? -ne 0 ]; then
+   echo "Failed to run pmount." 1>&2
+   exit 1
+fi
+#Obtain the list of databases.
+showall=`$mdb showall`
+if [ $? -ne 0 ]; then
+   echo "Failed to run mdb." 1>&2
+   exit 1
+fi
+
+#Determine the node the web server is running on.
+web_node=`enstore conf $timeout --show crons web_node`
+if [ -z "$web_node" ]; then
+   echo "Unable to determine web server node." 1>&2
+   exit 1
+fi
+#Determine the directory on the web server to copy the output to.
+html_dir=`enstore conf $timeout --show crons html_dir`
+if [ -z "$html_dir" ]; then
+   echo "Unable to determine html directory." 1>&2
+   exit 1
+fi
+
+#Get the alias name if available.
+www_alias=`enstore conf $timeout --show crons www_alias` #optional in config
+if [ $? -ne 0 ]; then
+   www_alias=`hostname | cut -f 1 -d "."`
+fi
+f=/tmp/${www_alias}_pnfsExports.html
+
+#Send the output for making the web page to the temporary file.
+(
+echo '<html> <head> <title>PNFS Exports Page</title> </head> <body>'
+echo '<body bgcolor="#ffffff" text=#a0a0ff">'
+echo '<h1><center>PNFS Exports Page </center><h1><hr>'
+echo "<h1><center>PNFS Information: `date`</center><h1>"
+
+echo '<pre>'
+echo "$showall"
+echo '</pre><hr>'
+
+echo "<h1><center>PNFS ExportList Fetch Begin: `date`</center><h1><hr>"
+echo '<table bgcolor="#dfdff0" nosave>'
+echo -e "<tr>\n"
+
+col=0
+for host in `echo $hostlist`; do
+   if [ $col -eq $NUMCOLUMNS ]; then
+      echo -e "</tr>\n <tr>"
+      col=0
+   fi
+   col=`expr $col + 1`
+   echo '<td> <pre>'
+   
+   show_host_info=`$pmount show host $host`
+   echo "$show_host_info" 
+   
+   echo '</pre> </td>'
+done
+
+echo '</table>'
+echo "<h1><center>PNFS ExportList Fetch Done: `date`</center><h1><hr>"
+echo '</html>'
+) > $f
+
+#This copy should still work if the pnfs and web servers are on the same node.
+chown enstore.enstore $f
+chmod 755 $f
+enrcp $f $web_node:$html_dir
 
 
