Make as SDE ready as is possible.

diff --git a/sbin/rdist-log b/sbin/rdist-log
--- a/sbin/rdist-log
+++ b/sbin/rdist-log
@@ -1,4 +1,8 @@
 #!/bin/sh
+# bin/$RCSfile$  $Revision$
+
+# script to backup enstore log files to the backup node
+
 set -u  # force better programming and ability to use check for not set
 if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
 
@@ -6,12 +10,19 @@ if [ "${1:-}" = "-x" ] ; then set -xv; shift; fi
 gang=`gang`
 thisNode=${gang}srv2
 rdistNode=${gang}srv3.fnal.gov
-filePath='/diska'
-ENSTORE=/home/enstore/enstore
 
-# bin/$RCSfile$  $Revision$
-
-# script to backup enstore log files to the backup node
+#Check if ENSTORE_DIR is set.
+if [ -z `echo $ENSTORE_DIR` ]; then
+   echo "ENSTORE_DIR not set."
+   exit 1
+fi
+#Get the log directory.
+filePath=`enstore conf --show crons log_dir`
+if [ $? -ne 0 ]; then
+   echo "Unable to obtain log directory."
+   exit 1
+fi
+filePathBackup=${filePath}-backup
 
 # function to list command, execute it and list status
 doit() { echo "$1"
@@ -26,12 +37,13 @@ if uname -n | grep ${thisNode} > /dev/null; then
 
 # cron is scheduled every 15 minutes, so time out after 10
 
- cmd="/usr/bin/rsync -e $ENSTORE/sbin/enrsh -rlpgtx --delete --timeout=600 --blocking-io \
-      ${filePath}/enstore-log/LOG-* enstore@${rdistNode}:${filePath}/enstore-log-backup"
+ cmd="/usr/bin/rsync -e $ENSTORE_DIR/sbin/enrsh -rlpgtx --delete \
+      --timeout=600 --blocking-io \
+      ${filePath}/LOG-* enstore@${rdistNode}:${filePathBackup}"
  doit "$cmd"
 
 else
-  echo "Do not know about node `uname -n`... fix $ENSTORE/sbin/rdist-log script"
+  echo "Do not know about node `uname -n`... fix $ENSTORE_DIR/sbin/rdist-log script"
   exit 1
 fi
 
