Fixed a bug to deal with the possibility that my setuid program is not there.

diff --git a/tools/encp_test_functions b/tools/encp_test_functions
--- a/tools/encp_test_functions
+++ b/tools/encp_test_functions
@@ -590,6 +590,12 @@ setuid_read_write_test()
     section="SETUID READ AND WRITE"
     print_test_name $section
     
+    which setuid > /dev/null 2>&1
+    if [ $? -ne 0 ]; then
+	echo "Unable to find setuid.  Skipping test and continuing."
+	return
+    fi
+
     truncate_encp_output
 
     #Snag a random file.
