Modified to support the encp regression testing using pnfs_agent in addition to a directly mounted pnfs mount point.

diff --git a/tools/encp_test_functions b/tools/encp_test_functions
--- a/tools/encp_test_functions
+++ b/tools/encp_test_functions
@@ -1,4 +1,4 @@
-#! /bin/bash
+#! /bin/sh
 
 #LOCAL_DIR=/tmp
 #PNFS_DIR=/pnfs/mist
@@ -12,6 +12,42 @@ if [ ! -d "$PNFS_DIR" ]; then
     exit 1
 fi
 
+#Handle making files in PNFS through mountpoint or pnfs_agent.
+make_pnfs_dir()
+{
+    if [ -n "$REMOTE_ENCP" ]; then
+        enstore pnfs_agent --mkdirs $1
+    else
+        mkdir -p $1
+    fi
+}
+#Handle removing a directory.
+rm_pnfs_file()
+{
+    if [ -n "$REMOTE_ENCP" ]; then
+        enstore pnfs_agent --remove $1
+    else
+        rm -f $1
+    fi
+}
+#Handle cleanup of files (both normal and in pnfs).
+cleanup_files()
+{
+    for file in `eval echo $*`; do
+        if [ "$file" = "/dev/null" ]; then
+            continue
+        fi
+
+	if [ -f $file ]; then
+	    rm $file
+        else
+	    if [ $? -ne 0 ]; then
+                rm_pnfs_file $file
+            fi
+        fi
+    done
+}
+
 LOCAL_INPUT_DIR=$LOCAL_DIR/test_files
 LOCAL_OUTPUT_DIR=$LOCAL_DIR/encp_test
 PNFS_INPUT_DIR=$PNFS_DIR/test_files
@@ -19,6 +55,11 @@ PNFS_OUTPUT_DIR=$PNFS_DIR/encp_test
 PNFS_AGENT_OUTPUT_DIR=$PNFS_OUTPUT_DIR
 
 PNFS_HOSTNAME=`enstore conf --retries 3 --timeout 3 --show pnfs_agent | grep hostip | cut -f 4 -d "'"`
+
+if [ -z "$PNFS_HOSTNAME" ]; then
+    echo "Unable to obtain pnfs_agent information from configuration server."
+    exit 1
+fi
 
 ENSYNC_INPUT_DIR=$LOCAL_INPUT_DIR/ensync_test
 ENSYNC_OUTPUT_DIR=$PNFS_DIR/NULL/ensync_test
@@ -29,13 +70,23 @@ touch $ENCP_OUTPUT
 
 encp_create_tests
 mkdir -p $LOCAL_OUTPUT_DIR
-mkdir -p $PNFS_INPUT_DIR
-mkdir -p $PNFS_OUTPUT_DIR
+make_pnfs_dir $PNFS_INPUT_DIR
+make_pnfs_dir $PNFS_OUTPUT_DIR
+
 #Make test pnfs files.
 for fname in `ls $LOCAL_INPUT_DIR`; do
-    if [ -f $LOCAL_INPUT_DIR/$fname -a ! -f $PNFS_INPUT_DIR/$fname ]; then
+    #Handle using mounted pnfs filesystem or using pnfs agent.
+    if [ -n "$REMOTE_ENCP" ]; then
+        enstore pnfs_agent --exists $PNFS_INPUT_DIR/$fname
+        pnfs_test=$?
+    else
+        test -f $PNFS_INPUT_DIR/$fname
+        pnfs_test=$?
+    fi
+    if [ -f $LOCAL_INPUT_DIR/$fname -a ! $pnfs_test ]; then
 	#We set the file family to volume_read_test for the benifit of the
 	# volume read test.
+        echo encp --file-family volume_read_test $LOCAL_INPUT_DIR/$fname $PNFS_INPUT_DIR/$fname
 	encp --file-family volume_read_test $LOCAL_INPUT_DIR/$fname $PNFS_INPUT_DIR/$fname
     fi
 done
@@ -76,17 +127,38 @@ get_file_list()
     echo "$filenames"
 }
 
+get_pnfs_file_list()
+{
+#$1 = directory of file to choose from
+
+    #Restrict this to files less than 100MB in size.
+    if [ -n $REMOTE_ENCP ]; then
+	#filenames=`enstore pnfs_agent --just-files --list-dir $1 | sed "s:^:$1/:"`
+	filenames=`enstore pnfs_agent --just-files --list-dir $1`
+    else
+        filenames=`find $1 -size -104857600c -type f`
+    fi
+
+    echo "$filenames"
+}
+
 get_volume_from_filename()
 {
 #$1 = pnfs filename to get the volume
     filename=$1
     
-    #Determine the layer 4 filename.
-    layer4_filename=`dirname $filename; echo "/.(use)(4)("; basename $filename; echo ")"`
-    layer4_filename=`echo $layer4_filename | tr -d " "`
+    
+    if [ -n $REMOTE_ENCP ]; then
+	#Rip just the volume out of the layer 4.
+	volume=`enstore pnfs_agent --layer 4 $filename | sed -n '1p'`
+    else
+        #Determine the layer 4 filename.
+	layer4_filename=`dirname $filename; echo "/.(use)(4)("; basename $filename; echo ")"`
+	layer4_filename=`echo $layer4_filename | tr -d " "`
 	
-    #Rip just the volume out of the layer 4.
-    volume=`cat $layer4_filename | sed -n '1p'`
+        #Rip just the volume out of the layer 4.
+	volume=`cat $layer4_filename | sed -n '1p'`
+    fi
 
     echo $volume
 }
@@ -128,6 +200,8 @@ absfile()
     echo $abs_filenames
 }
 
+#############################################################################
+
 #transfer file
 transfer()
 {
@@ -154,11 +228,12 @@ transfer()
     if [ "$rtn" -gt 0 ]; then
 	echo "$message TEST FAILED ON $direction"
 	cat $ENCP_OUTPUT
-	for file in $cleanup; do
-	    if [ "$file" != "dev/null" ]; then
-		rm -f $file
-	    fi
-	done
+	cleanup_files "$cleanup"
+	#for file in $cleanup; do
+	#    if [ "$file" != "/dev/null" ]; then
+	#	rm -f $file
+	#    fi
+	#done
 	exit 1
     fi
 }
@@ -183,7 +258,7 @@ volume_assert()
 	echo "$message TEST FAILED"
 	cat $ENCP_OUTPUT
 	for file in $cleanup; do
-	    if [ "$file" != "dev/null" ]; then
+	    if [ "$file" != "/dev/null" ]; then
 		rm -f $file
 	    fi
 	done
@@ -212,7 +287,7 @@ ensync_transfer()
 	echo "$message TEST FAILED"
 	cat $ENCP_OUTPUT
 	for file in $cleanup; do
-	    if [ "$file" != "dev/null" ]; then
+	    if [ "$file" != "/dev/null" ]; then
 		rm -f $file
 	    fi
 	done
@@ -220,7 +295,12 @@ ensync_transfer()
     fi
 }
 
+#############################################################################
+
 #Test if the original input and the final output files are the same.
+###
+### This does does not work with pnfs_agent.
+###
 test_diff()
 {
     infiles=`eval echo $1`
@@ -256,13 +336,21 @@ test_layer()
     message=`eval echo $2`
     
     for file in $pnfsfiles; do
-	result=`enstore pnfs --bfid $file`
+	if [ -n REMOTE_ENCP ]; then
+            enstore pnfs_agent --layer 1 $file > /dev/null
+        else
+	    enstore pnfs --layer $file 1 > /dev/null
+	fi
 	if [ $? -ne 0 ]; then
 	    echo $message "TEST FAILED ON LAYER"
 	    echo No bfid value: $result: $file
 	    return 1
 	fi
-	result=`enstore pnfs --layer $file`
+	if [ -n $REMOTE_ENCP ]; then
+	    result=`enstore pnfs_agent --layer 4 $file`
+	else
+	    result=`enstore pnfs --layer $file 4`
+	fi
 	for line in result; do
 	    if [ $line = "unknown" ]; then
 		echo $message "TEST FAILED ON LAYER"
@@ -276,6 +364,9 @@ test_layer()
 }
 
 #Test that the permissions are the same.
+###
+### This does does not work with pnfs_agent.
+###
 permissions_test()
 {
     infiles=`eval echo $1`
@@ -303,6 +394,9 @@ permissions_test()
 }
 
 #Test that the sizes are the same.
+###
+### This does does not work with pnfs_agent.
+###
 size_test()
 {
     infiles=`eval echo $1`
@@ -398,6 +492,7 @@ enstore_check_test()
     fi
 }
 
+#############################################################################
 
 single_read_test()
 {
@@ -407,7 +502,7 @@ single_read_test()
     truncate_encp_output
 
     #Snag a random file.
-    filelist=`get_file_list "$PNFS_INPUT_DIR"`
+    filelist=`get_pnfs_file_list "$PNFS_INPUT_DIR"`
     if [ -z "$filelist" ]; then
 	echo "Input directory empty.  Skipping test and continuing."
     else
@@ -417,28 +512,6 @@ single_read_test()
 	transfer encp '$filename' '$outname' '$outname' "" "$section" READ
     fi
 }
-
-#single_stken_read_test()
-#{
-#    section="SINGLE STKEN READ"
-#    print_test_name $section
-#    directory_to_use="/pnfs/test/zalokar/test"
-#    encp="encp --delayed-dismount 2"
-#
-#    truncate_encp_output
-#    
-#    #Snag a random file.
-#    filelist=`get_file_list "$directory_to_use"`
-#    if [ -z "$filelist" ]; then
-#	echo "Input directory empty.  Skipping test and continuing."
-#    else
-#	filename=`pick_random_files 1 $filelist`
-#	outname=/dev/null
-#	
-#	transfer '$encp' '$filename' '$outname' '$outname' "" "$section" READ
-#    fi
-#}
-
 
 single_read_write_test()
 {
@@ -457,15 +530,16 @@ single_read_write_test()
     transfer encp '$filename' '$pnfsname' '$pnfsname' "" "$section" WRITE
 
     test_layer '$pnfsname' "$section"
-    
+
     transfer encp '$pnfsname' '$outname' '$pnfsname $outname' "" "$Section" READ
 
     test_diff '$filename' '$outname' '$pnfsname $outname' "$section"
     permissions_test '$filename' '$outname' '$pnfsname $outname' "$section"
     size_test '$filename' '$outname' '$pnfsname $outname' "$section"
 
-    rm -f $outname
-    rm -f $pnfsname
+    #rm -f $outname
+    #rm_pnfs_file $pnfsname
+    cleanup_files '"$outname" "$pnfsname"'
 }
 
 
@@ -492,8 +566,9 @@ multiple_read_write_test()
     permissions_test '$filenames' '$outnames' '$pnfsnames $outnames' "$section"
     size_test '$filenames' '$outnames' '$pnfsnames $outnames' "$section"
 
-    rm -f $outnames
-    rm -f $pnfsnames
+    #rm -f $outnames
+    #rm_pnfs_file $pnfsnames
+    cleanup_files '"$outnames" "$pnfsnames"'
 }
 
 
@@ -523,10 +598,16 @@ dcache_read_write_test()
     pnfsname=`absfile $PNFS_OUTPUT_DIR $basename`
 
     #Create the output file, set the size and get the pnfs id.
-    touch $pnfsname
     size=`ls -l $filename | sed 's/ \{1,30\}/ /g' | cut -f 5 "-d "`
-    enstore pnfs --size "${pnfsname}" "${size}"
-    pnfsid=`enstore pnfs --id $pnfsname`
+    if [ -n $REMOTE_ENCP ]; then
+	enstore pnfs_agent --touch $pnfsname
+	enstore pnfs_agent --size "${pnfsname}" "${size}"
+	pnfsid=`enstore pnfs_agent --id $pnfsname`
+    else
+        touch $pnfsname
+	enstore pnfs --size "${pnfsname}" "${size}"
+	pnfsid=`enstore pnfs --id $pnfsname`
+    fi
 
     #Shorten some things for readability.
     #encp="encp --shortcut"
@@ -557,8 +638,9 @@ dcache_read_write_test()
     permissions_test '$filename' '$outname' '$pnfsname $outname' "$section"
     size_test '$filename' '$outname' '$pnfsnames $outname' "$section"
 
-    rm -f $outname
-    rm -f $pnfsname
+    #rm -f $outname
+    #rm_pnfs_file $pnfsname
+    cleanup_files '"$outname" "$pnfsname"'
 }
 
 non_conf_read_write_test()
@@ -588,8 +670,9 @@ non_conf_read_write_test()
     permissions_test '$filename' '$outname' '$pnfsname $outname' "$section"
     size_test '$filename' '$outname' '$pnfsnames $outname' "$section"
 
-    rm -f $outname
-    rm -f $pnfsname
+    #rm -f $outname
+    #rm_pnfs_file $pnfsname
+    cleanup_files '"$outname" "$pnfsname"'
 }
 
 setuid_read_write_test()
@@ -645,9 +728,10 @@ setuid_read_write_test()
     size_test '$filename' '$outname' '$pnfsnames $outname' "$section"
 
     setuid rm -f $outname
-    setuid rm -f $pnfsname
+    setuid rm_pnfs_file $pnfsname
     #setroot rm -f $outname
-    #setroot rm -f $pnfsname
+    #setroot rm_pnfs_file $pnfsname
+    setuid cleanup_files '"$outname" "$pnfsname"' 
 }
 
 single_threaded_read_write_test()
@@ -675,8 +759,9 @@ single_threaded_read_write_test()
     permissions_test '$filename' '$outname' '$pnfsname $outname' "$section"
     size_test '$filename' '$outname' '$pnfsname $outname' "$section"
 
-    rm -f $outname
-    rm -f $pnfsname
+    #rm -f $outname
+    #rm_pnfs_file $pnfsname
+    cleanup_files '"$outname" "$pnfsname"'
 }
 
 multiple_threaded_read_write_test()
@@ -703,8 +788,9 @@ multiple_threaded_read_write_test()
     permissions_test '$filenames' '$outnames' '$pnfsnames $outnames' "$section"
     size_test '$filenames' '$outnames' '$pnfsnames $outnames' "$section"
 
-    rm -f $outnames
-    rm -f $pnfsnames
+    #rm -f $outnames
+    #rm_pnfs_file $pnfsnames
+    cleanup_files '"$outnames" "$pnfsnames"'
 }
 
 single_ecrc_read_write_test()
@@ -732,8 +818,9 @@ single_ecrc_read_write_test()
     permissions_test '$filename' '$outname' '$pnfsname $outname' "$section"
     size_test '$filename' '$outname' '$pnfsname $outname' "$section"
 
-    rm -f $outname
-    rm -f $pnfsname
+    #rm -f $outname
+    #rm_pnfs_file $pnfsname
+    cleanup_files '"$outname" "$pnfsname"'
 }
 
 
@@ -760,7 +847,7 @@ single_assert_test()
     truncate_encp_output
     
     #Snag a random file.
-    filelist=`get_file_list "$PNFS_INPUT_DIR"`
+    filelist=`get_pnfs_file_list "$PNFS_INPUT_DIR"`
     if [ -z "$filelist" ]; then
 	echo "Input directory empty.  Skipping test and continuing."
     else
@@ -800,32 +887,37 @@ single_relative_path_read_write_test()
 
     truncate_encp_output
     
-    cwd=`pwd`
+    if [ -n "$REMOTE_ENCP" ]; then
+	echo "Detected using pnfs_agent.  Skipping test and continuing."
+    else
+	cwd=`pwd`
 
-    #Snag a random file.
-    filelist=`get_file_list "$LOCAL_INPUT_DIR"`
-    filename=`pick_random_files 1 $filelist`
-    basename=`basename $filename`
-    #pnfsname=`echo ${PNFS_OUTPUT_DIR}/$basename`
-    pnfsname=`echo $basename`
-    outname=`echo ${LOCAL_OUTPUT_DIR}/$basename`
+        #Snag a random file.
+	filelist=`get_file_list "$LOCAL_INPUT_DIR"`
+	filename=`pick_random_files 1 $filelist`
+	basename=`basename $filename`
+        #pnfsname=`echo ${PNFS_OUTPUT_DIR}/$basename`
+	pnfsname=`echo $basename`
+	outname=`echo ${LOCAL_OUTPUT_DIR}/$basename`
 
-    cd ${PNFS_OUTPUT_DIR}/
+	cd ${PNFS_OUTPUT_DIR}/
 
-    transfer encp '$filename' '$pnfsname' '$pnfsname' "" "$section" WRITE
+	transfer encp '$filename' '$pnfsname' '$pnfsname' "" "$section" WRITE
+	
+	test_layer '$pnfsname' "$section"
+	
+	transfer encp '$pnfsname' '$outname' '$pnfsname $outname' "" "$Section" READ
 
-    test_layer '$pnfsname' "$section"
-    
-    transfer encp '$pnfsname' '$outname' '$pnfsname $outname' "" "$Section" READ
-
-    test_diff '$filename' '$outname' '$pnfsname $outname' "$section"
-    permissions_test '$filename' '$outname' '$pnfsname $outname' "$section"
-    size_test '$filename' '$outname' '$pnfsname $outname' "$section"
-
-    rm -f $outname
-    rm -f $pnfsname
-
-    cd $cwd
+	test_diff '$filename' '$outname' '$pnfsname $outname' "$section"
+	permissions_test '$filename' '$outname' '$pnfsname $outname' "$section"
+	size_test '$filename' '$outname' '$pnfsname $outname' "$section"
+	
+        #rm -f $outname
+        #rm_pnfs_file $pnfsname
+	cleanup_files '"$outname" "$pnfsname"'
+	
+	cd $cwd
+    fi
 }
 
 single_local_pnfs_path_read_test()
@@ -836,7 +928,7 @@ single_local_pnfs_path_read_test()
     truncate_encp_output
 
     #Snag a random file.
-    filelist=`get_file_list "$PNFS_INPUT_DIR"`
+    filelist=`get_pnfs_file_list "$PNFS_INPUT_DIR"`
     if [ -z "$filelist" ]; then
 	echo "Input directory empty.  Skipping test and continuing."
     else
@@ -915,7 +1007,7 @@ single_fs_path_read_test()
     truncate_encp_output
 
     #Snag a random file.
-    filelist=`get_file_list "$PNFS_INPUT_DIR"`
+    filelist=`get_pnfs_file_list "$PNFS_INPUT_DIR"`
     if [ -z "$filelist" ]; then
 	echo "Input directory empty.  Skipping test and continuing."
     else
@@ -956,8 +1048,9 @@ data_access_layer_read_write_test()
     permissions_test '$filename' '$outname' '$pnfsname $outname' "$section"
     size_test '$filename' '$outname' '$pnfsname $outname' "$section"
 
-    rm -f $outname
-    rm -f $pnfsname
+    #rm -f $outname
+    #rm_pnfs_file $pnfsname
+    cleanup_files '"$outname" "$pnfsname"'
 
     cd $cwd
 }
@@ -1008,8 +1101,9 @@ multiple_copies_read_write_test()
 	#Now read back the copy via copy number.
 	transfer "encp --copy 1" '$pnfsname' '$outname' '$pnfsname $outname' "" "$Section" READ
 
-	rm -f $outname
-	rm -f $pnfsname
+	#rm -f $outname
+	#rm_pnfs_file $pnfsname
+        cleanup_files '"$outname" "$pnfsname"'
     fi
 }
 
@@ -1066,9 +1160,9 @@ pnfs_agent_read_write_test()
 	transfer "$encp" "$pnfsname" '$outname' '$pnfsname $outname' "" "$section" READ
     fi
     
-    #Make sure kshell is enabled on the target node.
-    rsh $PNFS_HOSTNAME "rm -f $pnfsname" > /dev/null 2>&1
-    rm -f $outname
+    #rm -f $outname
+    #rm_pnfs_file $pnfsname
+    cleanup_files '"$outname" "$pnfsname"'
 }
 
 pipe_write_test()
@@ -1110,7 +1204,8 @@ pipe_write_test()
 	
 	transfer encp "$pnfsname" '$outname' '$pnfsname $outname' "" "$section" READ
 
-	rm -f $outname
-	rm -f $pnfsname
+	#rm -f $outname
+	#rm_pnfs_file $pnfsname
+        cleanup_files '"$outname" "$pnfsname"'
     fi
 }
